//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWeb.LineaCarritoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="LineaCarritoWS.LineaCarritoWS")]
    public interface LineaCarritoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/LineaCarritoWS/ListarLineaCarritoPorIdCarrit" +
            "oRequest", ReplyAction="http://services.softprog.pucp.edu.pe/LineaCarritoWS/ListarLineaCarritoPorIdCarrit" +
            "oResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoResponse ListarLineaCarritoPorIdCarrito(SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/LineaCarritoWS/ListarLineaCarritoPorIdCarrit" +
            "oRequest", ReplyAction="http://services.softprog.pucp.edu.pe/LineaCarritoWS/ListarLineaCarritoPorIdCarrit" +
            "oResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoResponse> ListarLineaCarritoPorIdCarritoAsync(SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoRequest request);
        
        // CODEGEN: El parámetro 'lineaCarrito' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/LineaCarritoWS/InsertarLineaCarritoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/LineaCarritoWS/InsertarLineaCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoResponse InsertarLineaCarrito(SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/LineaCarritoWS/InsertarLineaCarritoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/LineaCarritoWS/InsertarLineaCarritoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoResponse> InsertarLineaCarritoAsync(SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/LineaCarritoWS/listarLineaCarritoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/LineaCarritoWS/listarLineaCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.LineaCarritoWS.listarLineaCarritoResponse listarLineaCarrito(SoftProgWeb.LineaCarritoWS.listarLineaCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/LineaCarritoWS/listarLineaCarritoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/LineaCarritoWS/listarLineaCarritoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.listarLineaCarritoResponse> listarLineaCarritoAsync(SoftProgWeb.LineaCarritoWS.listarLineaCarritoRequest request);
        
        // CODEGEN: El parámetro 'lineaCarrito' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/LineaCarritoWS/ActualizarLineaCarritoRequest" +
            "", ReplyAction="http://services.softprog.pucp.edu.pe/LineaCarritoWS/ActualizarLineaCarritoRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoResponse ActualizarLineaCarrito(SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/LineaCarritoWS/ActualizarLineaCarritoRequest" +
            "", ReplyAction="http://services.softprog.pucp.edu.pe/LineaCarritoWS/ActualizarLineaCarritoRespons" +
            "e")]
        System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoResponse> ActualizarLineaCarritoAsync(SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoRequest request);
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/LineaCarritoWS/EliminarLineaCarritoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/LineaCarritoWS/EliminarLineaCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoResponse EliminarLineaCarrito(SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/LineaCarritoWS/EliminarLineaCarritoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/LineaCarritoWS/EliminarLineaCarritoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoResponse> EliminarLineaCarritoAsync(SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/LineaCarritoWS/ObtenerLineaCarritoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/LineaCarritoWS/ObtenerLineaCarritoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoResponse ObtenerLineaCarrito(SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/LineaCarritoWS/ObtenerLineaCarritoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/LineaCarritoWS/ObtenerLineaCarritoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoResponse> ObtenerLineaCarritoAsync(SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class lineaCarrito : registro {
        
        private int cantidadField;
        
        private carritoCompras carritoComprasField;
        
        private double precioVolumenField;
        
        private producto productoField;
        
        private double subTotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public carritoCompras carritoCompras {
            get {
                return this.carritoComprasField;
            }
            set {
                this.carritoComprasField = value;
                this.RaisePropertyChanged("carritoCompras");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double precioVolumen {
            get {
                return this.precioVolumenField;
            }
            set {
                this.precioVolumenField = value;
                this.RaisePropertyChanged("precioVolumen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double subTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
                this.RaisePropertyChanged("subTotal");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class carritoCompras : registro {
        
        private cliente clienteField;
        
        private estadoCarrito estadoField;
        
        private bool estadoFieldSpecified;
        
        private string estadoStringField;
        
        private double totalConDescuentoField;
        
        private double totalParcialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoCarrito estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estadoString {
            get {
                return this.estadoStringField;
            }
            set {
                this.estadoStringField = value;
                this.RaisePropertyChanged("estadoString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double totalConDescuento {
            get {
                return this.totalConDescuentoField;
            }
            set {
                this.totalConDescuentoField = value;
                this.RaisePropertyChanged("totalConDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double totalParcial {
            get {
                return this.totalParcialField;
            }
            set {
                this.totalParcialField = value;
                this.RaisePropertyChanged("totalParcial");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cliente : persona {
        
        private categoriaCliente categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string categoriaClienteField;
        
        private double lineaCreditoField;
        
        private int numeroPedidosHistoricoField;
        
        private int numeroPedidosMensualProField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaCliente categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string categoriaCliente {
            get {
                return this.categoriaClienteField;
            }
            set {
                this.categoriaClienteField = value;
                this.RaisePropertyChanged("categoriaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double lineaCredito {
            get {
                return this.lineaCreditoField;
            }
            set {
                this.lineaCreditoField = value;
                this.RaisePropertyChanged("lineaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int numeroPedidosHistorico {
            get {
                return this.numeroPedidosHistoricoField;
            }
            set {
                this.numeroPedidosHistoricoField = value;
                this.RaisePropertyChanged("numeroPedidosHistorico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroPedidosMensualPro {
            get {
                return this.numeroPedidosMensualProField;
            }
            set {
                this.numeroPedidosMensualProField = value;
                this.RaisePropertyChanged("numeroPedidosMensualPro");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum categoriaCliente {
        
        /// <remarks/>
        DISTRIBUIDOR,
        
        /// <remarks/>
        REVENDEDOR,
        
        /// <remarks/>
        RESTAURANTE,
        
        /// <remarks/>
        HOTEL,
        
        /// <remarks/>
        CATERING,
        
        /// <remarks/>
        GOBIERNO,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class persona : registro {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private genero generoField;
        
        private bool generoFieldSpecified;
        
        private string generoStringField;
        
        private string nombreField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public genero genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified {
            get {
                return this.generoFieldSpecified;
            }
            set {
                this.generoFieldSpecified = value;
                this.RaisePropertyChanged("generoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string generoString {
            get {
                return this.generoStringField;
            }
            set {
                this.generoStringField = value;
                this.RaisePropertyChanged("generoString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum genero {
        
        /// <remarks/>
        HOMBRE,
        
        /// <remarks/>
        MUJER,
        
        /// <remarks/>
        NO_ESPECIFICADO,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(categoriaProducto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(producto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(carritoCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lineaCarrito))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class registro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class categoriaProducto : registro {
        
        private categoriaProducto categoriaPadreField;
        
        private string descripcionField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaProducto categoriaPadre {
            get {
                return this.categoriaPadreField;
            }
            set {
                this.categoriaPadreField = value;
                this.RaisePropertyChanged("categoriaPadre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class producto : registro {
        
        private categoriaProducto categoriaField;
        
        private string descripcionField;
        
        private string marcaField;
        
        private unidadMedida medidaAlMayorField;
        
        private bool medidaAlMayorFieldSpecified;
        
        private string medidaAlMayorStringField;
        
        private string nombreField;
        
        private double precioAlMayorField;
        
        private double precioUnitarioField;
        
        private string sKUField;
        
        private int stockDisponibleField;
        
        private int stockMaximoField;
        
        private int stockMinimoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaProducto categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public unidadMedida medidaAlMayor {
            get {
                return this.medidaAlMayorField;
            }
            set {
                this.medidaAlMayorField = value;
                this.RaisePropertyChanged("medidaAlMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool medidaAlMayorSpecified {
            get {
                return this.medidaAlMayorFieldSpecified;
            }
            set {
                this.medidaAlMayorFieldSpecified = value;
                this.RaisePropertyChanged("medidaAlMayorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string medidaAlMayorString {
            get {
                return this.medidaAlMayorStringField;
            }
            set {
                this.medidaAlMayorStringField = value;
                this.RaisePropertyChanged("medidaAlMayorString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double precioAlMayor {
            get {
                return this.precioAlMayorField;
            }
            set {
                this.precioAlMayorField = value;
                this.RaisePropertyChanged("precioAlMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
                this.RaisePropertyChanged("SKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int stockDisponible {
            get {
                return this.stockDisponibleField;
            }
            set {
                this.stockDisponibleField = value;
                this.RaisePropertyChanged("stockDisponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int stockMaximo {
            get {
                return this.stockMaximoField;
            }
            set {
                this.stockMaximoField = value;
                this.RaisePropertyChanged("stockMaximo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int stockMinimo {
            get {
                return this.stockMinimoField;
            }
            set {
                this.stockMinimoField = value;
                this.RaisePropertyChanged("stockMinimo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum unidadMedida {
        
        /// <remarks/>
        KILOGRAMO,
        
        /// <remarks/>
        LITRO,
        
        /// <remarks/>
        GALON,
        
        /// <remarks/>
        BOTELLA,
        
        /// <remarks/>
        CAJA,
        
        /// <remarks/>
        PAQUETE,
        
        /// <remarks/>
        SACO,
        
        /// <remarks/>
        PACK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum estadoCarrito {
        
        /// <remarks/>
        VACIO,
        
        /// <remarks/>
        EN_PROCESO,
        
        /// <remarks/>
        EN_REVISION,
        
        /// <remarks/>
        CONFIRMADO,
        
        /// <remarks/>
        CANCELADO,
        
        /// <remarks/>
        EXPIRADO,
        
        /// <remarks/>
        COMPLETADO,
        
        /// <remarks/>
        PENDIENTE,
        
        /// <remarks/>
        PROCESADO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarLineaCarritoPorIdCarrito", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class ListarLineaCarritoPorIdCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public ListarLineaCarritoPorIdCarritoRequest() {
        }
        
        public ListarLineaCarritoPorIdCarritoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarLineaCarritoPorIdCarritoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class ListarLineaCarritoPorIdCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.LineaCarritoWS.lineaCarrito[] @return;
        
        public ListarLineaCarritoPorIdCarritoResponse() {
        }
        
        public ListarLineaCarritoPorIdCarritoResponse(SoftProgWeb.LineaCarritoWS.lineaCarrito[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarLineaCarrito", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class InsertarLineaCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.LineaCarritoWS.lineaCarrito lineaCarrito;
        
        public InsertarLineaCarritoRequest() {
        }
        
        public InsertarLineaCarritoRequest(SoftProgWeb.LineaCarritoWS.lineaCarrito lineaCarrito) {
            this.lineaCarrito = lineaCarrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertarLineaCarritoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class InsertarLineaCarritoResponse {
        
        public InsertarLineaCarritoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarLineaCarrito", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarLineaCarritoRequest {
        
        public listarLineaCarritoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarLineaCarritoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarLineaCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.LineaCarritoWS.lineaCarrito[] @return;
        
        public listarLineaCarritoResponse() {
        }
        
        public listarLineaCarritoResponse(SoftProgWeb.LineaCarritoWS.lineaCarrito[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarLineaCarrito", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class ActualizarLineaCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.LineaCarritoWS.lineaCarrito lineaCarrito;
        
        public ActualizarLineaCarritoRequest() {
        }
        
        public ActualizarLineaCarritoRequest(SoftProgWeb.LineaCarritoWS.lineaCarrito lineaCarrito) {
            this.lineaCarrito = lineaCarrito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarLineaCarritoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class ActualizarLineaCarritoResponse {
        
        public ActualizarLineaCarritoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarLineaCarrito", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class EliminarLineaCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public EliminarLineaCarritoRequest() {
        }
        
        public EliminarLineaCarritoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarLineaCarritoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class EliminarLineaCarritoResponse {
        
        public EliminarLineaCarritoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerLineaCarrito", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class ObtenerLineaCarritoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public ObtenerLineaCarritoRequest() {
        }
        
        public ObtenerLineaCarritoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerLineaCarritoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class ObtenerLineaCarritoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.LineaCarritoWS.lineaCarrito @return;
        
        public ObtenerLineaCarritoResponse() {
        }
        
        public ObtenerLineaCarritoResponse(SoftProgWeb.LineaCarritoWS.lineaCarrito @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LineaCarritoWSChannel : SoftProgWeb.LineaCarritoWS.LineaCarritoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LineaCarritoWSClient : System.ServiceModel.ClientBase<SoftProgWeb.LineaCarritoWS.LineaCarritoWS>, SoftProgWeb.LineaCarritoWS.LineaCarritoWS {
        
        public LineaCarritoWSClient() {
        }
        
        public LineaCarritoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LineaCarritoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LineaCarritoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LineaCarritoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoResponse SoftProgWeb.LineaCarritoWS.LineaCarritoWS.ListarLineaCarritoPorIdCarrito(SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoRequest request) {
            return base.Channel.ListarLineaCarritoPorIdCarrito(request);
        }
        
        public SoftProgWeb.LineaCarritoWS.lineaCarrito[] ListarLineaCarritoPorIdCarrito(int id) {
            SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoRequest inValue = new SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoRequest();
            inValue.id = id;
            SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoResponse retVal = ((SoftProgWeb.LineaCarritoWS.LineaCarritoWS)(this)).ListarLineaCarritoPorIdCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoResponse> SoftProgWeb.LineaCarritoWS.LineaCarritoWS.ListarLineaCarritoPorIdCarritoAsync(SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoRequest request) {
            return base.Channel.ListarLineaCarritoPorIdCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoResponse> ListarLineaCarritoPorIdCarritoAsync(int id) {
            SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoRequest inValue = new SoftProgWeb.LineaCarritoWS.ListarLineaCarritoPorIdCarritoRequest();
            inValue.id = id;
            return ((SoftProgWeb.LineaCarritoWS.LineaCarritoWS)(this)).ListarLineaCarritoPorIdCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoResponse SoftProgWeb.LineaCarritoWS.LineaCarritoWS.InsertarLineaCarrito(SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoRequest request) {
            return base.Channel.InsertarLineaCarrito(request);
        }
        
        public void InsertarLineaCarrito(SoftProgWeb.LineaCarritoWS.lineaCarrito lineaCarrito) {
            SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoRequest inValue = new SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoRequest();
            inValue.lineaCarrito = lineaCarrito;
            SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoResponse retVal = ((SoftProgWeb.LineaCarritoWS.LineaCarritoWS)(this)).InsertarLineaCarrito(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoResponse> SoftProgWeb.LineaCarritoWS.LineaCarritoWS.InsertarLineaCarritoAsync(SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoRequest request) {
            return base.Channel.InsertarLineaCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoResponse> InsertarLineaCarritoAsync(SoftProgWeb.LineaCarritoWS.lineaCarrito lineaCarrito) {
            SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoRequest inValue = new SoftProgWeb.LineaCarritoWS.InsertarLineaCarritoRequest();
            inValue.lineaCarrito = lineaCarrito;
            return ((SoftProgWeb.LineaCarritoWS.LineaCarritoWS)(this)).InsertarLineaCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.LineaCarritoWS.listarLineaCarritoResponse SoftProgWeb.LineaCarritoWS.LineaCarritoWS.listarLineaCarrito(SoftProgWeb.LineaCarritoWS.listarLineaCarritoRequest request) {
            return base.Channel.listarLineaCarrito(request);
        }
        
        public SoftProgWeb.LineaCarritoWS.lineaCarrito[] listarLineaCarrito() {
            SoftProgWeb.LineaCarritoWS.listarLineaCarritoRequest inValue = new SoftProgWeb.LineaCarritoWS.listarLineaCarritoRequest();
            SoftProgWeb.LineaCarritoWS.listarLineaCarritoResponse retVal = ((SoftProgWeb.LineaCarritoWS.LineaCarritoWS)(this)).listarLineaCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.listarLineaCarritoResponse> SoftProgWeb.LineaCarritoWS.LineaCarritoWS.listarLineaCarritoAsync(SoftProgWeb.LineaCarritoWS.listarLineaCarritoRequest request) {
            return base.Channel.listarLineaCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.listarLineaCarritoResponse> listarLineaCarritoAsync() {
            SoftProgWeb.LineaCarritoWS.listarLineaCarritoRequest inValue = new SoftProgWeb.LineaCarritoWS.listarLineaCarritoRequest();
            return ((SoftProgWeb.LineaCarritoWS.LineaCarritoWS)(this)).listarLineaCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoResponse SoftProgWeb.LineaCarritoWS.LineaCarritoWS.ActualizarLineaCarrito(SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoRequest request) {
            return base.Channel.ActualizarLineaCarrito(request);
        }
        
        public void ActualizarLineaCarrito(SoftProgWeb.LineaCarritoWS.lineaCarrito lineaCarrito) {
            SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoRequest inValue = new SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoRequest();
            inValue.lineaCarrito = lineaCarrito;
            SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoResponse retVal = ((SoftProgWeb.LineaCarritoWS.LineaCarritoWS)(this)).ActualizarLineaCarrito(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoResponse> SoftProgWeb.LineaCarritoWS.LineaCarritoWS.ActualizarLineaCarritoAsync(SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoRequest request) {
            return base.Channel.ActualizarLineaCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoResponse> ActualizarLineaCarritoAsync(SoftProgWeb.LineaCarritoWS.lineaCarrito lineaCarrito) {
            SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoRequest inValue = new SoftProgWeb.LineaCarritoWS.ActualizarLineaCarritoRequest();
            inValue.lineaCarrito = lineaCarrito;
            return ((SoftProgWeb.LineaCarritoWS.LineaCarritoWS)(this)).ActualizarLineaCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoResponse SoftProgWeb.LineaCarritoWS.LineaCarritoWS.EliminarLineaCarrito(SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoRequest request) {
            return base.Channel.EliminarLineaCarrito(request);
        }
        
        public void EliminarLineaCarrito(int id) {
            SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoRequest inValue = new SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoRequest();
            inValue.id = id;
            SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoResponse retVal = ((SoftProgWeb.LineaCarritoWS.LineaCarritoWS)(this)).EliminarLineaCarrito(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoResponse> SoftProgWeb.LineaCarritoWS.LineaCarritoWS.EliminarLineaCarritoAsync(SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoRequest request) {
            return base.Channel.EliminarLineaCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoResponse> EliminarLineaCarritoAsync(int id) {
            SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoRequest inValue = new SoftProgWeb.LineaCarritoWS.EliminarLineaCarritoRequest();
            inValue.id = id;
            return ((SoftProgWeb.LineaCarritoWS.LineaCarritoWS)(this)).EliminarLineaCarritoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoResponse SoftProgWeb.LineaCarritoWS.LineaCarritoWS.ObtenerLineaCarrito(SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoRequest request) {
            return base.Channel.ObtenerLineaCarrito(request);
        }
        
        public SoftProgWeb.LineaCarritoWS.lineaCarrito ObtenerLineaCarrito(int id) {
            SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoRequest inValue = new SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoRequest();
            inValue.id = id;
            SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoResponse retVal = ((SoftProgWeb.LineaCarritoWS.LineaCarritoWS)(this)).ObtenerLineaCarrito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoResponse> SoftProgWeb.LineaCarritoWS.LineaCarritoWS.ObtenerLineaCarritoAsync(SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoRequest request) {
            return base.Channel.ObtenerLineaCarritoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoResponse> ObtenerLineaCarritoAsync(int id) {
            SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoRequest inValue = new SoftProgWeb.LineaCarritoWS.ObtenerLineaCarritoRequest();
            inValue.id = id;
            return ((SoftProgWeb.LineaCarritoWS.LineaCarritoWS)(this)).ObtenerLineaCarritoAsync(inValue);
        }
    }
}
