//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWeb.ServicioDescuentoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="ServicioDescuentoWS.DescuentoWS")]
    public interface DescuentoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/DescuentoWS/listarDescuentoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/DescuentoWS/listarDescuentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServicioDescuentoWS.listarDescuentoResponse listarDescuento(SoftProgWeb.ServicioDescuentoWS.listarDescuentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/DescuentoWS/listarDescuentoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/DescuentoWS/listarDescuentoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.listarDescuentoResponse> listarDescuentoAsync(SoftProgWeb.ServicioDescuentoWS.listarDescuentoRequest request);
        
        // CODEGEN: El parámetro 'descuento' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/DescuentoWS/insertarDescuentoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/DescuentoWS/insertarDescuentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServicioDescuentoWS.insertarDescuentoResponse insertarDescuento(SoftProgWeb.ServicioDescuentoWS.insertarDescuentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/DescuentoWS/insertarDescuentoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/DescuentoWS/insertarDescuentoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.insertarDescuentoResponse> insertarDescuentoAsync(SoftProgWeb.ServicioDescuentoWS.insertarDescuentoRequest request);
        
        // CODEGEN: El parámetro 'descuento' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/DescuentoWS/actualizarDescuentoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/DescuentoWS/actualizarDescuentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoResponse actualizarDescuento(SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/DescuentoWS/actualizarDescuentoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/DescuentoWS/actualizarDescuentoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoResponse> actualizarDescuentoAsync(SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoRequest request);
        
        // CODEGEN: El parámetro 'id' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/DescuentoWS/eliminarDescuentoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/DescuentoWS/eliminarDescuentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoResponse eliminarDescuento(SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/DescuentoWS/eliminarDescuentoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/DescuentoWS/eliminarDescuentoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoResponse> eliminarDescuentoAsync(SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/DescuentoWS/obtenerDescuentoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/DescuentoWS/obtenerDescuentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoResponse obtenerDescuento(SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/DescuentoWS/obtenerDescuentoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/DescuentoWS/obtenerDescuentoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoResponse> obtenerDescuentoAsync(SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class descuento : registro {
        
        private int cantidadMaxField;
        
        private int cantidadMinField;
        
        private double precioPorVolumenField;
        
        private producto productoField;
        
        private tipoDescuento tipoDescuentoField;
        
        private bool tipoDescuentoFieldSpecified;
        
        private string tipoDescuentoStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadMax {
            get {
                return this.cantidadMaxField;
            }
            set {
                this.cantidadMaxField = value;
                this.RaisePropertyChanged("cantidadMax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadMin {
            get {
                return this.cantidadMinField;
            }
            set {
                this.cantidadMinField = value;
                this.RaisePropertyChanged("cantidadMin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double precioPorVolumen {
            get {
                return this.precioPorVolumenField;
            }
            set {
                this.precioPorVolumenField = value;
                this.RaisePropertyChanged("precioPorVolumen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public tipoDescuento tipoDescuento {
            get {
                return this.tipoDescuentoField;
            }
            set {
                this.tipoDescuentoField = value;
                this.RaisePropertyChanged("tipoDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDescuentoSpecified {
            get {
                return this.tipoDescuentoFieldSpecified;
            }
            set {
                this.tipoDescuentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDescuentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoDescuentoString {
            get {
                return this.tipoDescuentoStringField;
            }
            set {
                this.tipoDescuentoStringField = value;
                this.RaisePropertyChanged("tipoDescuentoString");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class producto : registro {
        
        private categoriaProducto categoriaField;
        
        private string descripcionField;
        
        private string marcaField;
        
        private unidadMedida medidaAlMayorField;
        
        private bool medidaAlMayorFieldSpecified;
        
        private string medidaAlMayorStringField;
        
        private string nombreField;
        
        private double precioAlMayorField;
        
        private double precioUnitarioField;
        
        private string sKUField;
        
        private int stockDisponibleField;
        
        private int stockMaximoField;
        
        private int stockMinimoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaProducto categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public unidadMedida medidaAlMayor {
            get {
                return this.medidaAlMayorField;
            }
            set {
                this.medidaAlMayorField = value;
                this.RaisePropertyChanged("medidaAlMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool medidaAlMayorSpecified {
            get {
                return this.medidaAlMayorFieldSpecified;
            }
            set {
                this.medidaAlMayorFieldSpecified = value;
                this.RaisePropertyChanged("medidaAlMayorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string medidaAlMayorString {
            get {
                return this.medidaAlMayorStringField;
            }
            set {
                this.medidaAlMayorStringField = value;
                this.RaisePropertyChanged("medidaAlMayorString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double precioAlMayor {
            get {
                return this.precioAlMayorField;
            }
            set {
                this.precioAlMayorField = value;
                this.RaisePropertyChanged("precioAlMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
                this.RaisePropertyChanged("SKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int stockDisponible {
            get {
                return this.stockDisponibleField;
            }
            set {
                this.stockDisponibleField = value;
                this.RaisePropertyChanged("stockDisponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int stockMaximo {
            get {
                return this.stockMaximoField;
            }
            set {
                this.stockMaximoField = value;
                this.RaisePropertyChanged("stockMaximo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int stockMinimo {
            get {
                return this.stockMinimoField;
            }
            set {
                this.stockMinimoField = value;
                this.RaisePropertyChanged("stockMinimo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class categoriaProducto : registro {
        
        private categoriaProducto categoriaPadreField;
        
        private string descripcionField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaProducto categoriaPadre {
            get {
                return this.categoriaPadreField;
            }
            set {
                this.categoriaPadreField = value;
                this.RaisePropertyChanged("categoriaPadre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(categoriaProducto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(producto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(descuento))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class registro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum unidadMedida {
        
        /// <remarks/>
        KILOGRAMO,
        
        /// <remarks/>
        LITRO,
        
        /// <remarks/>
        GALON,
        
        /// <remarks/>
        BOTELLA,
        
        /// <remarks/>
        CAJA,
        
        /// <remarks/>
        PAQUETE,
        
        /// <remarks/>
        SACO,
        
        /// <remarks/>
        PACK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum tipoDescuento {
        
        /// <remarks/>
        PRIMERA_COMPRA,
        
        /// <remarks/>
        DESC_TEMPORADA,
        
        /// <remarks/>
        CLIENTE_FRECUENTE,
        
        /// <remarks/>
        DESC_PERSONALIZADO,
        
        /// <remarks/>
        SIN_DESCUENTO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDescuento", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDescuentoRequest {
        
        public listarDescuentoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDescuentoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDescuentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioDescuentoWS.descuento[] @return;
        
        public listarDescuentoResponse() {
        }
        
        public listarDescuentoResponse(SoftProgWeb.ServicioDescuentoWS.descuento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDescuento", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarDescuentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioDescuentoWS.descuento descuento;
        
        public insertarDescuentoRequest() {
        }
        
        public insertarDescuentoRequest(SoftProgWeb.ServicioDescuentoWS.descuento descuento) {
            this.descuento = descuento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDescuentoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarDescuentoResponse {
        
        public insertarDescuentoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarDescuento", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarDescuentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioDescuentoWS.descuento descuento;
        
        public actualizarDescuentoRequest() {
        }
        
        public actualizarDescuentoRequest(SoftProgWeb.ServicioDescuentoWS.descuento descuento) {
            this.descuento = descuento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarDescuentoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarDescuentoResponse {
        
        public actualizarDescuentoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDescuento", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarDescuentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarDescuentoRequest() {
        }
        
        public eliminarDescuentoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDescuentoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarDescuentoResponse {
        
        public eliminarDescuentoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDescuento", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerDescuentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerDescuentoRequest() {
        }
        
        public obtenerDescuentoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDescuentoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerDescuentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioDescuentoWS.descuento @return;
        
        public obtenerDescuentoResponse() {
        }
        
        public obtenerDescuentoResponse(SoftProgWeb.ServicioDescuentoWS.descuento @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DescuentoWSChannel : SoftProgWeb.ServicioDescuentoWS.DescuentoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DescuentoWSClient : System.ServiceModel.ClientBase<SoftProgWeb.ServicioDescuentoWS.DescuentoWS>, SoftProgWeb.ServicioDescuentoWS.DescuentoWS {
        
        public DescuentoWSClient() {
        }
        
        public DescuentoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DescuentoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DescuentoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DescuentoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioDescuentoWS.listarDescuentoResponse SoftProgWeb.ServicioDescuentoWS.DescuentoWS.listarDescuento(SoftProgWeb.ServicioDescuentoWS.listarDescuentoRequest request) {
            return base.Channel.listarDescuento(request);
        }
        
        public SoftProgWeb.ServicioDescuentoWS.descuento[] listarDescuento() {
            SoftProgWeb.ServicioDescuentoWS.listarDescuentoRequest inValue = new SoftProgWeb.ServicioDescuentoWS.listarDescuentoRequest();
            SoftProgWeb.ServicioDescuentoWS.listarDescuentoResponse retVal = ((SoftProgWeb.ServicioDescuentoWS.DescuentoWS)(this)).listarDescuento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.listarDescuentoResponse> SoftProgWeb.ServicioDescuentoWS.DescuentoWS.listarDescuentoAsync(SoftProgWeb.ServicioDescuentoWS.listarDescuentoRequest request) {
            return base.Channel.listarDescuentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.listarDescuentoResponse> listarDescuentoAsync() {
            SoftProgWeb.ServicioDescuentoWS.listarDescuentoRequest inValue = new SoftProgWeb.ServicioDescuentoWS.listarDescuentoRequest();
            return ((SoftProgWeb.ServicioDescuentoWS.DescuentoWS)(this)).listarDescuentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioDescuentoWS.insertarDescuentoResponse SoftProgWeb.ServicioDescuentoWS.DescuentoWS.insertarDescuento(SoftProgWeb.ServicioDescuentoWS.insertarDescuentoRequest request) {
            return base.Channel.insertarDescuento(request);
        }
        
        public void insertarDescuento(SoftProgWeb.ServicioDescuentoWS.descuento descuento) {
            SoftProgWeb.ServicioDescuentoWS.insertarDescuentoRequest inValue = new SoftProgWeb.ServicioDescuentoWS.insertarDescuentoRequest();
            inValue.descuento = descuento;
            SoftProgWeb.ServicioDescuentoWS.insertarDescuentoResponse retVal = ((SoftProgWeb.ServicioDescuentoWS.DescuentoWS)(this)).insertarDescuento(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.insertarDescuentoResponse> SoftProgWeb.ServicioDescuentoWS.DescuentoWS.insertarDescuentoAsync(SoftProgWeb.ServicioDescuentoWS.insertarDescuentoRequest request) {
            return base.Channel.insertarDescuentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.insertarDescuentoResponse> insertarDescuentoAsync(SoftProgWeb.ServicioDescuentoWS.descuento descuento) {
            SoftProgWeb.ServicioDescuentoWS.insertarDescuentoRequest inValue = new SoftProgWeb.ServicioDescuentoWS.insertarDescuentoRequest();
            inValue.descuento = descuento;
            return ((SoftProgWeb.ServicioDescuentoWS.DescuentoWS)(this)).insertarDescuentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoResponse SoftProgWeb.ServicioDescuentoWS.DescuentoWS.actualizarDescuento(SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoRequest request) {
            return base.Channel.actualizarDescuento(request);
        }
        
        public void actualizarDescuento(SoftProgWeb.ServicioDescuentoWS.descuento descuento) {
            SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoRequest inValue = new SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoRequest();
            inValue.descuento = descuento;
            SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoResponse retVal = ((SoftProgWeb.ServicioDescuentoWS.DescuentoWS)(this)).actualizarDescuento(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoResponse> SoftProgWeb.ServicioDescuentoWS.DescuentoWS.actualizarDescuentoAsync(SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoRequest request) {
            return base.Channel.actualizarDescuentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoResponse> actualizarDescuentoAsync(SoftProgWeb.ServicioDescuentoWS.descuento descuento) {
            SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoRequest inValue = new SoftProgWeb.ServicioDescuentoWS.actualizarDescuentoRequest();
            inValue.descuento = descuento;
            return ((SoftProgWeb.ServicioDescuentoWS.DescuentoWS)(this)).actualizarDescuentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoResponse SoftProgWeb.ServicioDescuentoWS.DescuentoWS.eliminarDescuento(SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoRequest request) {
            return base.Channel.eliminarDescuento(request);
        }
        
        public void eliminarDescuento(int id) {
            SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoRequest inValue = new SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoRequest();
            inValue.id = id;
            SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoResponse retVal = ((SoftProgWeb.ServicioDescuentoWS.DescuentoWS)(this)).eliminarDescuento(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoResponse> SoftProgWeb.ServicioDescuentoWS.DescuentoWS.eliminarDescuentoAsync(SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoRequest request) {
            return base.Channel.eliminarDescuentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoResponse> eliminarDescuentoAsync(int id) {
            SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoRequest inValue = new SoftProgWeb.ServicioDescuentoWS.eliminarDescuentoRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServicioDescuentoWS.DescuentoWS)(this)).eliminarDescuentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoResponse SoftProgWeb.ServicioDescuentoWS.DescuentoWS.obtenerDescuento(SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoRequest request) {
            return base.Channel.obtenerDescuento(request);
        }
        
        public SoftProgWeb.ServicioDescuentoWS.descuento obtenerDescuento(int id) {
            SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoRequest inValue = new SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoRequest();
            inValue.id = id;
            SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoResponse retVal = ((SoftProgWeb.ServicioDescuentoWS.DescuentoWS)(this)).obtenerDescuento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoResponse> SoftProgWeb.ServicioDescuentoWS.DescuentoWS.obtenerDescuentoAsync(SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoRequest request) {
            return base.Channel.obtenerDescuentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoResponse> obtenerDescuentoAsync(int id) {
            SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoRequest inValue = new SoftProgWeb.ServicioDescuentoWS.obtenerDescuentoRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServicioDescuentoWS.DescuentoWS)(this)).obtenerDescuentoAsync(inValue);
        }
    }
}
