//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWeb.CarritoComprasWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="CarritoComprasWS.CarritoComprasWS")]
    public interface CarritoComprasWS {
        
        // CODEGEN: Parameter 'carritoCompras' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CarritoComprasWS/actualizarCarritoComprasReq" +
            "uest", ReplyAction="http://services.softprog.pucp.edu.pe/CarritoComprasWS/actualizarCarritoComprasRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasResponse actualizarCarritoCompras(SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CarritoComprasWS/actualizarCarritoComprasReq" +
            "uest", ReplyAction="http://services.softprog.pucp.edu.pe/CarritoComprasWS/actualizarCarritoComprasRes" +
            "ponse")]
        System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasResponse> actualizarCarritoComprasAsync(SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CarritoComprasWS/listarTodosCarritoComprasRe" +
            "quest", ReplyAction="http://services.softprog.pucp.edu.pe/CarritoComprasWS/listarTodosCarritoComprasRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasResponse listarTodosCarritoCompras(SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CarritoComprasWS/listarTodosCarritoComprasRe" +
            "quest", ReplyAction="http://services.softprog.pucp.edu.pe/CarritoComprasWS/listarTodosCarritoComprasRe" +
            "sponse")]
        System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasResponse> listarTodosCarritoComprasAsync(SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CarritoComprasWS/eliminarCarritoComprasReque" +
            "st", ReplyAction="http://services.softprog.pucp.edu.pe/CarritoComprasWS/eliminarCarritoComprasRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasResponse eliminarCarritoCompras(SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CarritoComprasWS/eliminarCarritoComprasReque" +
            "st", ReplyAction="http://services.softprog.pucp.edu.pe/CarritoComprasWS/eliminarCarritoComprasRespo" +
            "nse")]
        System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasResponse> eliminarCarritoComprasAsync(SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CarritoComprasWS/obtenerCarritoComprasReques" +
            "t", ReplyAction="http://services.softprog.pucp.edu.pe/CarritoComprasWS/obtenerCarritoComprasRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasResponse obtenerCarritoCompras(SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CarritoComprasWS/obtenerCarritoComprasReques" +
            "t", ReplyAction="http://services.softprog.pucp.edu.pe/CarritoComprasWS/obtenerCarritoComprasRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasResponse> obtenerCarritoComprasAsync(SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasRequest request);
        
        // CODEGEN: Parameter 'carritoCompras' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CarritoComprasWS/insertarCarritoComprasReque" +
            "st", ReplyAction="http://services.softprog.pucp.edu.pe/CarritoComprasWS/insertarCarritoComprasRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.CarritoComprasWS.insertarCarritoComprasResponse insertarCarritoCompras(SoftProgWeb.CarritoComprasWS.insertarCarritoComprasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CarritoComprasWS/insertarCarritoComprasReque" +
            "st", ReplyAction="http://services.softprog.pucp.edu.pe/CarritoComprasWS/insertarCarritoComprasRespo" +
            "nse")]
        System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.insertarCarritoComprasResponse> insertarCarritoComprasAsync(SoftProgWeb.CarritoComprasWS.insertarCarritoComprasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class carritoCompras : registro {
        
        private cliente clienteField;
        
        private estadoCarrito estadoField;
        
        private bool estadoFieldSpecified;
        
        private string estadoStringField;
        
        private double totalConDescuentoField;
        
        private double totalParcialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoCarrito estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estadoString {
            get {
                return this.estadoStringField;
            }
            set {
                this.estadoStringField = value;
                this.RaisePropertyChanged("estadoString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double totalConDescuento {
            get {
                return this.totalConDescuentoField;
            }
            set {
                this.totalConDescuentoField = value;
                this.RaisePropertyChanged("totalConDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double totalParcial {
            get {
                return this.totalParcialField;
            }
            set {
                this.totalParcialField = value;
                this.RaisePropertyChanged("totalParcial");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cliente : persona {
        
        private categoriaCliente categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string categoriaClienteField;
        
        private double lineaCreditoField;
        
        private int numeroPedidosHistoricoField;
        
        private int numeroPedidosMensualProField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaCliente categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string categoriaCliente {
            get {
                return this.categoriaClienteField;
            }
            set {
                this.categoriaClienteField = value;
                this.RaisePropertyChanged("categoriaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double lineaCredito {
            get {
                return this.lineaCreditoField;
            }
            set {
                this.lineaCreditoField = value;
                this.RaisePropertyChanged("lineaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int numeroPedidosHistorico {
            get {
                return this.numeroPedidosHistoricoField;
            }
            set {
                this.numeroPedidosHistoricoField = value;
                this.RaisePropertyChanged("numeroPedidosHistorico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroPedidosMensualPro {
            get {
                return this.numeroPedidosMensualProField;
            }
            set {
                this.numeroPedidosMensualProField = value;
                this.RaisePropertyChanged("numeroPedidosMensualPro");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum categoriaCliente {
        
        /// <remarks/>
        DISTRIBUIDOR,
        
        /// <remarks/>
        REVENDEDOR,
        
        /// <remarks/>
        RESTAURANTE,
        
        /// <remarks/>
        HOTEL,
        
        /// <remarks/>
        CATERING,
        
        /// <remarks/>
        GOBIERNO,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class persona : registro {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private genero generoField;
        
        private bool generoFieldSpecified;
        
        private string generoStringField;
        
        private string nombreField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public genero genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified {
            get {
                return this.generoFieldSpecified;
            }
            set {
                this.generoFieldSpecified = value;
                this.RaisePropertyChanged("generoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string generoString {
            get {
                return this.generoStringField;
            }
            set {
                this.generoStringField = value;
                this.RaisePropertyChanged("generoString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum genero {
        
        /// <remarks/>
        HOMBRE,
        
        /// <remarks/>
        MUJER,
        
        /// <remarks/>
        NO_ESPECIFICADO,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(carritoCompras))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class registro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum estadoCarrito {
        
        /// <remarks/>
        VACIO,
        
        /// <remarks/>
        EN_PROCESO,
        
        /// <remarks/>
        EN_REVISION,
        
        /// <remarks/>
        CONFIRMADO,
        
        /// <remarks/>
        CANCELADO,
        
        /// <remarks/>
        EXPIRADO,
        
        /// <remarks/>
        COMPLETADO,
        
        /// <remarks/>
        PENDIENTE,
        
        /// <remarks/>
        PROCESADO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCarritoCompras", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarCarritoComprasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.CarritoComprasWS.carritoCompras carritoCompras;
        
        public actualizarCarritoComprasRequest() {
        }
        
        public actualizarCarritoComprasRequest(SoftProgWeb.CarritoComprasWS.carritoCompras carritoCompras) {
            this.carritoCompras = carritoCompras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCarritoComprasResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarCarritoComprasResponse {
        
        public actualizarCarritoComprasResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosCarritoCompras", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosCarritoComprasRequest {
        
        public listarTodosCarritoComprasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosCarritoComprasResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosCarritoComprasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.CarritoComprasWS.carritoCompras[] @return;
        
        public listarTodosCarritoComprasResponse() {
        }
        
        public listarTodosCarritoComprasResponse(SoftProgWeb.CarritoComprasWS.carritoCompras[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCarritoCompras", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCarritoComprasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarCarritoComprasRequest() {
        }
        
        public eliminarCarritoComprasRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCarritoComprasResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCarritoComprasResponse {
        
        public eliminarCarritoComprasResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCarritoCompras", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCarritoComprasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerCarritoComprasRequest() {
        }
        
        public obtenerCarritoComprasRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCarritoComprasResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCarritoComprasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.CarritoComprasWS.carritoCompras @return;
        
        public obtenerCarritoComprasResponse() {
        }
        
        public obtenerCarritoComprasResponse(SoftProgWeb.CarritoComprasWS.carritoCompras @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCarritoCompras", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCarritoComprasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.CarritoComprasWS.carritoCompras carritoCompras;
        
        public insertarCarritoComprasRequest() {
        }
        
        public insertarCarritoComprasRequest(SoftProgWeb.CarritoComprasWS.carritoCompras carritoCompras) {
            this.carritoCompras = carritoCompras;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCarritoComprasResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCarritoComprasResponse {
        
        public insertarCarritoComprasResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarritoComprasWSChannel : SoftProgWeb.CarritoComprasWS.CarritoComprasWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarritoComprasWSClient : System.ServiceModel.ClientBase<SoftProgWeb.CarritoComprasWS.CarritoComprasWS>, SoftProgWeb.CarritoComprasWS.CarritoComprasWS {
        
        public CarritoComprasWSClient() {
        }
        
        public CarritoComprasWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarritoComprasWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarritoComprasWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarritoComprasWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasResponse SoftProgWeb.CarritoComprasWS.CarritoComprasWS.actualizarCarritoCompras(SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasRequest request) {
            return base.Channel.actualizarCarritoCompras(request);
        }
        
        public void actualizarCarritoCompras(SoftProgWeb.CarritoComprasWS.carritoCompras carritoCompras) {
            SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasRequest inValue = new SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasRequest();
            inValue.carritoCompras = carritoCompras;
            SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasResponse retVal = ((SoftProgWeb.CarritoComprasWS.CarritoComprasWS)(this)).actualizarCarritoCompras(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasResponse> SoftProgWeb.CarritoComprasWS.CarritoComprasWS.actualizarCarritoComprasAsync(SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasRequest request) {
            return base.Channel.actualizarCarritoComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasResponse> actualizarCarritoComprasAsync(SoftProgWeb.CarritoComprasWS.carritoCompras carritoCompras) {
            SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasRequest inValue = new SoftProgWeb.CarritoComprasWS.actualizarCarritoComprasRequest();
            inValue.carritoCompras = carritoCompras;
            return ((SoftProgWeb.CarritoComprasWS.CarritoComprasWS)(this)).actualizarCarritoComprasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasResponse SoftProgWeb.CarritoComprasWS.CarritoComprasWS.listarTodosCarritoCompras(SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasRequest request) {
            return base.Channel.listarTodosCarritoCompras(request);
        }
        
        public SoftProgWeb.CarritoComprasWS.carritoCompras[] listarTodosCarritoCompras() {
            SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasRequest inValue = new SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasRequest();
            SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasResponse retVal = ((SoftProgWeb.CarritoComprasWS.CarritoComprasWS)(this)).listarTodosCarritoCompras(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasResponse> SoftProgWeb.CarritoComprasWS.CarritoComprasWS.listarTodosCarritoComprasAsync(SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasRequest request) {
            return base.Channel.listarTodosCarritoComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasResponse> listarTodosCarritoComprasAsync() {
            SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasRequest inValue = new SoftProgWeb.CarritoComprasWS.listarTodosCarritoComprasRequest();
            return ((SoftProgWeb.CarritoComprasWS.CarritoComprasWS)(this)).listarTodosCarritoComprasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasResponse SoftProgWeb.CarritoComprasWS.CarritoComprasWS.eliminarCarritoCompras(SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasRequest request) {
            return base.Channel.eliminarCarritoCompras(request);
        }
        
        public void eliminarCarritoCompras(int id) {
            SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasRequest inValue = new SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasRequest();
            inValue.id = id;
            SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasResponse retVal = ((SoftProgWeb.CarritoComprasWS.CarritoComprasWS)(this)).eliminarCarritoCompras(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasResponse> SoftProgWeb.CarritoComprasWS.CarritoComprasWS.eliminarCarritoComprasAsync(SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasRequest request) {
            return base.Channel.eliminarCarritoComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasResponse> eliminarCarritoComprasAsync(int id) {
            SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasRequest inValue = new SoftProgWeb.CarritoComprasWS.eliminarCarritoComprasRequest();
            inValue.id = id;
            return ((SoftProgWeb.CarritoComprasWS.CarritoComprasWS)(this)).eliminarCarritoComprasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasResponse SoftProgWeb.CarritoComprasWS.CarritoComprasWS.obtenerCarritoCompras(SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasRequest request) {
            return base.Channel.obtenerCarritoCompras(request);
        }
        
        public SoftProgWeb.CarritoComprasWS.carritoCompras obtenerCarritoCompras(int id) {
            SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasRequest inValue = new SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasRequest();
            inValue.id = id;
            SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasResponse retVal = ((SoftProgWeb.CarritoComprasWS.CarritoComprasWS)(this)).obtenerCarritoCompras(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasResponse> SoftProgWeb.CarritoComprasWS.CarritoComprasWS.obtenerCarritoComprasAsync(SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasRequest request) {
            return base.Channel.obtenerCarritoComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasResponse> obtenerCarritoComprasAsync(int id) {
            SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasRequest inValue = new SoftProgWeb.CarritoComprasWS.obtenerCarritoComprasRequest();
            inValue.id = id;
            return ((SoftProgWeb.CarritoComprasWS.CarritoComprasWS)(this)).obtenerCarritoComprasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.CarritoComprasWS.insertarCarritoComprasResponse SoftProgWeb.CarritoComprasWS.CarritoComprasWS.insertarCarritoCompras(SoftProgWeb.CarritoComprasWS.insertarCarritoComprasRequest request) {
            return base.Channel.insertarCarritoCompras(request);
        }
        
        public void insertarCarritoCompras(SoftProgWeb.CarritoComprasWS.carritoCompras carritoCompras) {
            SoftProgWeb.CarritoComprasWS.insertarCarritoComprasRequest inValue = new SoftProgWeb.CarritoComprasWS.insertarCarritoComprasRequest();
            inValue.carritoCompras = carritoCompras;
            SoftProgWeb.CarritoComprasWS.insertarCarritoComprasResponse retVal = ((SoftProgWeb.CarritoComprasWS.CarritoComprasWS)(this)).insertarCarritoCompras(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.insertarCarritoComprasResponse> SoftProgWeb.CarritoComprasWS.CarritoComprasWS.insertarCarritoComprasAsync(SoftProgWeb.CarritoComprasWS.insertarCarritoComprasRequest request) {
            return base.Channel.insertarCarritoComprasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.CarritoComprasWS.insertarCarritoComprasResponse> insertarCarritoComprasAsync(SoftProgWeb.CarritoComprasWS.carritoCompras carritoCompras) {
            SoftProgWeb.CarritoComprasWS.insertarCarritoComprasRequest inValue = new SoftProgWeb.CarritoComprasWS.insertarCarritoComprasRequest();
            inValue.carritoCompras = carritoCompras;
            return ((SoftProgWeb.CarritoComprasWS.CarritoComprasWS)(this)).insertarCarritoComprasAsync(inValue);
        }
    }
}
