USE REDCOM;

SET SQL_SAFE_UPDATES = 0;

DELETE FROM LineaOrdenCompra;
DELETE FROM DetalleDeEnvio;
DELETE FROM OrdenCompra;
DELETE FROM LineaCarrito;
DELETE FROM CarritoDeCompras;
DELETE FROM CategoriaProducto_has_CategoriaProducto;
DELETE FROM CategoriaProducto;
DELETE FROM Descuento;
DELETE FROM Producto;
DELETE FROM Empresa;
DELETE FROM Cliente;
DELETE FROM Administrador;
DELETE FROM CuentaUsuario;

ALTER TABLE LineaOrdenCompra AUTO_INCREMENT = 1;
ALTER TABLE DetalleDeEnvio AUTO_INCREMENT = 1;
ALTER TABLE OrdenCompra AUTO_INCREMENT = 1;
ALTER TABLE LineaCarrito AUTO_INCREMENT = 1;
ALTER TABLE CarritoDeCompras AUTO_INCREMENT = 1;
ALTER TABLE CategoriaProducto AUTO_INCREMENT = 1;
ALTER TABLE Descuento AUTO_INCREMENT = 1;
ALTER TABLE Producto AUTO_INCREMENT = 1;
ALTER TABLE Empresa AUTO_INCREMENT = 1;
ALTER TABLE Cliente AUTO_INCREMENT = 1;
ALTER TABLE Administrador AUTO_INCREMENT = 1;
ALTER TABLE CuentaUsuario AUTO_INCREMENT = 1;