//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWeb.ServiceioProductoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="ServiceioProductoWS.ProductoWS")]
    public interface ProductoWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/obtenerPorSkuRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/obtenerPorSkuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServiceioProductoWS.obtenerPorSkuResponse obtenerPorSku(SoftProgWeb.ServiceioProductoWS.obtenerPorSkuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/obtenerPorSkuRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/obtenerPorSkuResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.obtenerPorSkuResponse> obtenerPorSkuAsync(SoftProgWeb.ServiceioProductoWS.obtenerPorSkuRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/listarProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/listarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServiceioProductoWS.listarProductoResponse listarProducto(SoftProgWeb.ServiceioProductoWS.listarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/listarProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/listarProductoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.listarProductoResponse> listarProductoAsync(SoftProgWeb.ServiceioProductoWS.listarProductoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/listarfiltrarProductoPorPrecioReq" +
            "uest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/listarfiltrarProductoPorPrecioRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioResponse listarfiltrarProductoPorPrecio(SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/listarfiltrarProductoPorPrecioReq" +
            "uest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/listarfiltrarProductoPorPrecioRes" +
            "ponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioResponse> listarfiltrarProductoPorPrecioAsync(SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/listarfiltrarProductoPorMarcaRequ" +
            "est", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/listarfiltrarProductoPorMarcaResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaResponse listarfiltrarProductoPorMarca(SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/listarfiltrarProductoPorMarcaRequ" +
            "est", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/listarfiltrarProductoPorMarcaResp" +
            "onse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaResponse> listarfiltrarProductoPorMarcaAsync(SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaRequest request);
        
        // CODEGEN: Parameter 'producto' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/insertarProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/insertarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServiceioProductoWS.insertarProductoResponse insertarProducto(SoftProgWeb.ServiceioProductoWS.insertarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/insertarProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/insertarProductoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.insertarProductoResponse> insertarProductoAsync(SoftProgWeb.ServiceioProductoWS.insertarProductoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/obtenerProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/obtenerProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServiceioProductoWS.obtenerProductoResponse obtenerProducto(SoftProgWeb.ServiceioProductoWS.obtenerProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/obtenerProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/obtenerProductoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.obtenerProductoResponse> obtenerProductoAsync(SoftProgWeb.ServiceioProductoWS.obtenerProductoRequest request);
        
        // CODEGEN: Parameter 'producto' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/actualizarProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/actualizarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServiceioProductoWS.actualizarProductoResponse actualizarProducto(SoftProgWeb.ServiceioProductoWS.actualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/actualizarProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/actualizarProductoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.actualizarProductoResponse> actualizarProductoAsync(SoftProgWeb.ServiceioProductoWS.actualizarProductoRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/eliminarProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/eliminarProductoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServiceioProductoWS.eliminarProductoResponse eliminarProducto(SoftProgWeb.ServiceioProductoWS.eliminarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ProductoWS/eliminarProductoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ProductoWS/eliminarProductoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.eliminarProductoResponse> eliminarProductoAsync(SoftProgWeb.ServiceioProductoWS.eliminarProductoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class producto : registro {
        
        private categoriaProducto categoriaField;
        
        private string descripcionField;
        
        private string marcaField;
        
        private unidadMedida medidaAlMayorField;
        
        private bool medidaAlMayorFieldSpecified;
        
        private string medidaAlMayorStringField;
        
        private string nombreField;
        
        private double precioAlMayorField;
        
        private double precioUnitarioField;
        
        private string sKUField;
        
        private int stockDisponibleField;
        
        private int stockMaximoField;
        
        private int stockMinimoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaProducto categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public unidadMedida medidaAlMayor {
            get {
                return this.medidaAlMayorField;
            }
            set {
                this.medidaAlMayorField = value;
                this.RaisePropertyChanged("medidaAlMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool medidaAlMayorSpecified {
            get {
                return this.medidaAlMayorFieldSpecified;
            }
            set {
                this.medidaAlMayorFieldSpecified = value;
                this.RaisePropertyChanged("medidaAlMayorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string medidaAlMayorString {
            get {
                return this.medidaAlMayorStringField;
            }
            set {
                this.medidaAlMayorStringField = value;
                this.RaisePropertyChanged("medidaAlMayorString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double precioAlMayor {
            get {
                return this.precioAlMayorField;
            }
            set {
                this.precioAlMayorField = value;
                this.RaisePropertyChanged("precioAlMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
                this.RaisePropertyChanged("SKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int stockDisponible {
            get {
                return this.stockDisponibleField;
            }
            set {
                this.stockDisponibleField = value;
                this.RaisePropertyChanged("stockDisponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int stockMaximo {
            get {
                return this.stockMaximoField;
            }
            set {
                this.stockMaximoField = value;
                this.RaisePropertyChanged("stockMaximo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int stockMinimo {
            get {
                return this.stockMinimoField;
            }
            set {
                this.stockMinimoField = value;
                this.RaisePropertyChanged("stockMinimo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class categoriaProducto : registro {
        
        private categoriaProducto categoriaPadreField;
        
        private string descripcionField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaProducto categoriaPadre {
            get {
                return this.categoriaPadreField;
            }
            set {
                this.categoriaPadreField = value;
                this.RaisePropertyChanged("categoriaPadre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(categoriaProducto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(producto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class registro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum unidadMedida {
        
        /// <remarks/>
        KILOGRAMO,
        
        /// <remarks/>
        LITRO,
        
        /// <remarks/>
        GALON,
        
        /// <remarks/>
        BOTELLA,
        
        /// <remarks/>
        CAJA,
        
        /// <remarks/>
        PAQUETE,
        
        /// <remarks/>
        SACO,
        
        /// <remarks/>
        PACK,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorSku", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorSkuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sku;
        
        public obtenerPorSkuRequest() {
        }
        
        public obtenerPorSkuRequest(string sku) {
            this.sku = sku;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorSkuResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorSkuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioProductoWS.producto @return;
        
        public obtenerPorSkuResponse() {
        }
        
        public obtenerPorSkuResponse(SoftProgWeb.ServiceioProductoWS.producto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductoRequest {
        
        public listarProductoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioProductoWS.producto[] @return;
        
        public listarProductoResponse() {
        }
        
        public listarProductoResponse(SoftProgWeb.ServiceioProductoWS.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarfiltrarProductoPorPrecio", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarfiltrarProductoPorPrecioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double rangoPrecio1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double rangoPrecio2;
        
        public listarfiltrarProductoPorPrecioRequest() {
        }
        
        public listarfiltrarProductoPorPrecioRequest(int id, double rangoPrecio1, double rangoPrecio2) {
            this.id = id;
            this.rangoPrecio1 = rangoPrecio1;
            this.rangoPrecio2 = rangoPrecio2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarfiltrarProductoPorPrecioResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarfiltrarProductoPorPrecioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioProductoWS.producto[] @return;
        
        public listarfiltrarProductoPorPrecioResponse() {
        }
        
        public listarfiltrarProductoPorPrecioResponse(SoftProgWeb.ServiceioProductoWS.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarfiltrarProductoPorMarca", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarfiltrarProductoPorMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RangoPrecio1;
        
        public listarfiltrarProductoPorMarcaRequest() {
        }
        
        public listarfiltrarProductoPorMarcaRequest(int id, string RangoPrecio1) {
            this.id = id;
            this.RangoPrecio1 = RangoPrecio1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarfiltrarProductoPorMarcaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarfiltrarProductoPorMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioProductoWS.producto[] @return;
        
        public listarfiltrarProductoPorMarcaResponse() {
        }
        
        public listarfiltrarProductoPorMarcaResponse(SoftProgWeb.ServiceioProductoWS.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioProductoWS.producto producto;
        
        public insertarProductoRequest() {
        }
        
        public insertarProductoRequest(SoftProgWeb.ServiceioProductoWS.producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarProductoResponse {
        
        public insertarProductoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerProductoRequest() {
        }
        
        public obtenerProductoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioProductoWS.producto @return;
        
        public obtenerProductoResponse() {
        }
        
        public obtenerProductoResponse(SoftProgWeb.ServiceioProductoWS.producto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioProductoWS.producto producto;
        
        public actualizarProductoRequest() {
        }
        
        public actualizarProductoRequest(SoftProgWeb.ServiceioProductoWS.producto producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarProductoResponse {
        
        public actualizarProductoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarProductoRequest() {
        }
        
        public eliminarProductoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarProductoResponse {
        
        public eliminarProductoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductoWSChannel : SoftProgWeb.ServiceioProductoWS.ProductoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoWSClient : System.ServiceModel.ClientBase<SoftProgWeb.ServiceioProductoWS.ProductoWS>, SoftProgWeb.ServiceioProductoWS.ProductoWS {
        
        public ProductoWSClient() {
        }
        
        public ProductoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioProductoWS.obtenerPorSkuResponse SoftProgWeb.ServiceioProductoWS.ProductoWS.obtenerPorSku(SoftProgWeb.ServiceioProductoWS.obtenerPorSkuRequest request) {
            return base.Channel.obtenerPorSku(request);
        }
        
        public SoftProgWeb.ServiceioProductoWS.producto obtenerPorSku(string sku) {
            SoftProgWeb.ServiceioProductoWS.obtenerPorSkuRequest inValue = new SoftProgWeb.ServiceioProductoWS.obtenerPorSkuRequest();
            inValue.sku = sku;
            SoftProgWeb.ServiceioProductoWS.obtenerPorSkuResponse retVal = ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).obtenerPorSku(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.obtenerPorSkuResponse> SoftProgWeb.ServiceioProductoWS.ProductoWS.obtenerPorSkuAsync(SoftProgWeb.ServiceioProductoWS.obtenerPorSkuRequest request) {
            return base.Channel.obtenerPorSkuAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.obtenerPorSkuResponse> obtenerPorSkuAsync(string sku) {
            SoftProgWeb.ServiceioProductoWS.obtenerPorSkuRequest inValue = new SoftProgWeb.ServiceioProductoWS.obtenerPorSkuRequest();
            inValue.sku = sku;
            return ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).obtenerPorSkuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioProductoWS.listarProductoResponse SoftProgWeb.ServiceioProductoWS.ProductoWS.listarProducto(SoftProgWeb.ServiceioProductoWS.listarProductoRequest request) {
            return base.Channel.listarProducto(request);
        }
        
        public SoftProgWeb.ServiceioProductoWS.producto[] listarProducto() {
            SoftProgWeb.ServiceioProductoWS.listarProductoRequest inValue = new SoftProgWeb.ServiceioProductoWS.listarProductoRequest();
            SoftProgWeb.ServiceioProductoWS.listarProductoResponse retVal = ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).listarProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.listarProductoResponse> SoftProgWeb.ServiceioProductoWS.ProductoWS.listarProductoAsync(SoftProgWeb.ServiceioProductoWS.listarProductoRequest request) {
            return base.Channel.listarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.listarProductoResponse> listarProductoAsync() {
            SoftProgWeb.ServiceioProductoWS.listarProductoRequest inValue = new SoftProgWeb.ServiceioProductoWS.listarProductoRequest();
            return ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).listarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioResponse SoftProgWeb.ServiceioProductoWS.ProductoWS.listarfiltrarProductoPorPrecio(SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioRequest request) {
            return base.Channel.listarfiltrarProductoPorPrecio(request);
        }
        
        public SoftProgWeb.ServiceioProductoWS.producto[] listarfiltrarProductoPorPrecio(int id, double rangoPrecio1, double rangoPrecio2) {
            SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioRequest inValue = new SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioRequest();
            inValue.id = id;
            inValue.rangoPrecio1 = rangoPrecio1;
            inValue.rangoPrecio2 = rangoPrecio2;
            SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioResponse retVal = ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).listarfiltrarProductoPorPrecio(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioResponse> SoftProgWeb.ServiceioProductoWS.ProductoWS.listarfiltrarProductoPorPrecioAsync(SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioRequest request) {
            return base.Channel.listarfiltrarProductoPorPrecioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioResponse> listarfiltrarProductoPorPrecioAsync(int id, double rangoPrecio1, double rangoPrecio2) {
            SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioRequest inValue = new SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorPrecioRequest();
            inValue.id = id;
            inValue.rangoPrecio1 = rangoPrecio1;
            inValue.rangoPrecio2 = rangoPrecio2;
            return ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).listarfiltrarProductoPorPrecioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaResponse SoftProgWeb.ServiceioProductoWS.ProductoWS.listarfiltrarProductoPorMarca(SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaRequest request) {
            return base.Channel.listarfiltrarProductoPorMarca(request);
        }
        
        public SoftProgWeb.ServiceioProductoWS.producto[] listarfiltrarProductoPorMarca(int id, string RangoPrecio1) {
            SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaRequest inValue = new SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaRequest();
            inValue.id = id;
            inValue.RangoPrecio1 = RangoPrecio1;
            SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaResponse retVal = ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).listarfiltrarProductoPorMarca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaResponse> SoftProgWeb.ServiceioProductoWS.ProductoWS.listarfiltrarProductoPorMarcaAsync(SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaRequest request) {
            return base.Channel.listarfiltrarProductoPorMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaResponse> listarfiltrarProductoPorMarcaAsync(int id, string RangoPrecio1) {
            SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaRequest inValue = new SoftProgWeb.ServiceioProductoWS.listarfiltrarProductoPorMarcaRequest();
            inValue.id = id;
            inValue.RangoPrecio1 = RangoPrecio1;
            return ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).listarfiltrarProductoPorMarcaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioProductoWS.insertarProductoResponse SoftProgWeb.ServiceioProductoWS.ProductoWS.insertarProducto(SoftProgWeb.ServiceioProductoWS.insertarProductoRequest request) {
            return base.Channel.insertarProducto(request);
        }
        
        public void insertarProducto(SoftProgWeb.ServiceioProductoWS.producto producto) {
            SoftProgWeb.ServiceioProductoWS.insertarProductoRequest inValue = new SoftProgWeb.ServiceioProductoWS.insertarProductoRequest();
            inValue.producto = producto;
            SoftProgWeb.ServiceioProductoWS.insertarProductoResponse retVal = ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).insertarProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.insertarProductoResponse> SoftProgWeb.ServiceioProductoWS.ProductoWS.insertarProductoAsync(SoftProgWeb.ServiceioProductoWS.insertarProductoRequest request) {
            return base.Channel.insertarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.insertarProductoResponse> insertarProductoAsync(SoftProgWeb.ServiceioProductoWS.producto producto) {
            SoftProgWeb.ServiceioProductoWS.insertarProductoRequest inValue = new SoftProgWeb.ServiceioProductoWS.insertarProductoRequest();
            inValue.producto = producto;
            return ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).insertarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioProductoWS.obtenerProductoResponse SoftProgWeb.ServiceioProductoWS.ProductoWS.obtenerProducto(SoftProgWeb.ServiceioProductoWS.obtenerProductoRequest request) {
            return base.Channel.obtenerProducto(request);
        }
        
        public SoftProgWeb.ServiceioProductoWS.producto obtenerProducto(int id) {
            SoftProgWeb.ServiceioProductoWS.obtenerProductoRequest inValue = new SoftProgWeb.ServiceioProductoWS.obtenerProductoRequest();
            inValue.id = id;
            SoftProgWeb.ServiceioProductoWS.obtenerProductoResponse retVal = ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).obtenerProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.obtenerProductoResponse> SoftProgWeb.ServiceioProductoWS.ProductoWS.obtenerProductoAsync(SoftProgWeb.ServiceioProductoWS.obtenerProductoRequest request) {
            return base.Channel.obtenerProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.obtenerProductoResponse> obtenerProductoAsync(int id) {
            SoftProgWeb.ServiceioProductoWS.obtenerProductoRequest inValue = new SoftProgWeb.ServiceioProductoWS.obtenerProductoRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).obtenerProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioProductoWS.actualizarProductoResponse SoftProgWeb.ServiceioProductoWS.ProductoWS.actualizarProducto(SoftProgWeb.ServiceioProductoWS.actualizarProductoRequest request) {
            return base.Channel.actualizarProducto(request);
        }
        
        public void actualizarProducto(SoftProgWeb.ServiceioProductoWS.producto producto) {
            SoftProgWeb.ServiceioProductoWS.actualizarProductoRequest inValue = new SoftProgWeb.ServiceioProductoWS.actualizarProductoRequest();
            inValue.producto = producto;
            SoftProgWeb.ServiceioProductoWS.actualizarProductoResponse retVal = ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).actualizarProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.actualizarProductoResponse> SoftProgWeb.ServiceioProductoWS.ProductoWS.actualizarProductoAsync(SoftProgWeb.ServiceioProductoWS.actualizarProductoRequest request) {
            return base.Channel.actualizarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.actualizarProductoResponse> actualizarProductoAsync(SoftProgWeb.ServiceioProductoWS.producto producto) {
            SoftProgWeb.ServiceioProductoWS.actualizarProductoRequest inValue = new SoftProgWeb.ServiceioProductoWS.actualizarProductoRequest();
            inValue.producto = producto;
            return ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).actualizarProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioProductoWS.eliminarProductoResponse SoftProgWeb.ServiceioProductoWS.ProductoWS.eliminarProducto(SoftProgWeb.ServiceioProductoWS.eliminarProductoRequest request) {
            return base.Channel.eliminarProducto(request);
        }
        
        public void eliminarProducto(int id) {
            SoftProgWeb.ServiceioProductoWS.eliminarProductoRequest inValue = new SoftProgWeb.ServiceioProductoWS.eliminarProductoRequest();
            inValue.id = id;
            SoftProgWeb.ServiceioProductoWS.eliminarProductoResponse retVal = ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).eliminarProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.eliminarProductoResponse> SoftProgWeb.ServiceioProductoWS.ProductoWS.eliminarProductoAsync(SoftProgWeb.ServiceioProductoWS.eliminarProductoRequest request) {
            return base.Channel.eliminarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioProductoWS.eliminarProductoResponse> eliminarProductoAsync(int id) {
            SoftProgWeb.ServiceioProductoWS.eliminarProductoRequest inValue = new SoftProgWeb.ServiceioProductoWS.eliminarProductoRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServiceioProductoWS.ProductoWS)(this)).eliminarProductoAsync(inValue);
        }
    }
}
