//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWeb.CategoriaProductoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="CategoriaProductoWS.CategoriaProductoWS")]
    public interface CategoriaProductoWS {
        
        // CODEGEN: Parameter 'categoriaProducto' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/actualizarCategoriaProdu" +
            "ctoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/actualizarCategoriaProdu" +
            "ctoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoResponse actualizarCategoriaProducto(SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/actualizarCategoriaProdu" +
            "ctoRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/actualizarCategoriaProdu" +
            "ctoResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoResponse> actualizarCategoriaProductoAsync(SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/listarCategoriaProductoR" +
            "equest", ReplyAction="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/listarCategoriaProductoR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoResponse listarCategoriaProducto(SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/listarCategoriaProductoR" +
            "equest", ReplyAction="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/listarCategoriaProductoR" +
            "esponse")]
        System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoResponse> listarCategoriaProductoAsync(SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/obtenerCategoriaProducto" +
            "Request", ReplyAction="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/obtenerCategoriaProducto" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoResponse obtenerCategoriaProducto(SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/obtenerCategoriaProducto" +
            "Request", ReplyAction="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/obtenerCategoriaProducto" +
            "Response")]
        System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoResponse> obtenerCategoriaProductoAsync(SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/eliminarCategoriaProduct" +
            "oRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/eliminarCategoriaProduct" +
            "oResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoResponse eliminarCategoriaProducto(SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/eliminarCategoriaProduct" +
            "oRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/eliminarCategoriaProduct" +
            "oResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoResponse> eliminarCategoriaProductoAsync(SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoRequest request);
        
        // CODEGEN: Parameter 'categoriaProducto' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/insertarCategoriaProduct" +
            "oRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/insertarCategoriaProduct" +
            "oResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoResponse insertarCategoriaProducto(SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/insertarCategoriaProduct" +
            "oRequest", ReplyAction="http://services.softprog.pucp.edu.pe/CategoriaProductoWS/insertarCategoriaProduct" +
            "oResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoResponse> insertarCategoriaProductoAsync(SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class categoriaProducto : registro {
        
        private string descripcionField;
        
        private int idCategoriaPadreField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCategoriaPadre {
            get {
                return this.idCategoriaPadreField;
            }
            set {
                this.idCategoriaPadreField = value;
                this.RaisePropertyChanged("idCategoriaPadre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(categoriaProducto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class registro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCategoriaProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarCategoriaProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.CategoriaProductoWS.categoriaProducto categoriaProducto;
        
        public actualizarCategoriaProductoRequest() {
        }
        
        public actualizarCategoriaProductoRequest(SoftProgWeb.CategoriaProductoWS.categoriaProducto categoriaProducto) {
            this.categoriaProducto = categoriaProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCategoriaProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarCategoriaProductoResponse {
        
        public actualizarCategoriaProductoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCategoriaProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCategoriaProductoRequest {
        
        public listarCategoriaProductoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCategoriaProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCategoriaProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.CategoriaProductoWS.categoriaProducto[] @return;
        
        public listarCategoriaProductoResponse() {
        }
        
        public listarCategoriaProductoResponse(SoftProgWeb.CategoriaProductoWS.categoriaProducto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCategoriaProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCategoriaProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerCategoriaProductoRequest() {
        }
        
        public obtenerCategoriaProductoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCategoriaProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCategoriaProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.CategoriaProductoWS.categoriaProducto @return;
        
        public obtenerCategoriaProductoResponse() {
        }
        
        public obtenerCategoriaProductoResponse(SoftProgWeb.CategoriaProductoWS.categoriaProducto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCategoriaProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCategoriaProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarCategoriaProductoRequest() {
        }
        
        public eliminarCategoriaProductoRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCategoriaProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCategoriaProductoResponse {
        
        public eliminarCategoriaProductoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCategoriaProducto", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCategoriaProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.CategoriaProductoWS.categoriaProducto categoriaProducto;
        
        public insertarCategoriaProductoRequest() {
        }
        
        public insertarCategoriaProductoRequest(SoftProgWeb.CategoriaProductoWS.categoriaProducto categoriaProducto) {
            this.categoriaProducto = categoriaProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCategoriaProductoResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCategoriaProductoResponse {
        
        public insertarCategoriaProductoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CategoriaProductoWSChannel : SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriaProductoWSClient : System.ServiceModel.ClientBase<SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS>, SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS {
        
        public CategoriaProductoWSClient() {
        }
        
        public CategoriaProductoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriaProductoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaProductoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaProductoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoResponse SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS.actualizarCategoriaProducto(SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoRequest request) {
            return base.Channel.actualizarCategoriaProducto(request);
        }
        
        public void actualizarCategoriaProducto(SoftProgWeb.CategoriaProductoWS.categoriaProducto categoriaProducto) {
            SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoRequest inValue = new SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoRequest();
            inValue.categoriaProducto = categoriaProducto;
            SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoResponse retVal = ((SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS)(this)).actualizarCategoriaProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoResponse> SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS.actualizarCategoriaProductoAsync(SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoRequest request) {
            return base.Channel.actualizarCategoriaProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoResponse> actualizarCategoriaProductoAsync(SoftProgWeb.CategoriaProductoWS.categoriaProducto categoriaProducto) {
            SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoRequest inValue = new SoftProgWeb.CategoriaProductoWS.actualizarCategoriaProductoRequest();
            inValue.categoriaProducto = categoriaProducto;
            return ((SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS)(this)).actualizarCategoriaProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoResponse SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS.listarCategoriaProducto(SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoRequest request) {
            return base.Channel.listarCategoriaProducto(request);
        }
        
        public SoftProgWeb.CategoriaProductoWS.categoriaProducto[] listarCategoriaProducto() {
            SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoRequest inValue = new SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoRequest();
            SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoResponse retVal = ((SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS)(this)).listarCategoriaProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoResponse> SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS.listarCategoriaProductoAsync(SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoRequest request) {
            return base.Channel.listarCategoriaProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoResponse> listarCategoriaProductoAsync() {
            SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoRequest inValue = new SoftProgWeb.CategoriaProductoWS.listarCategoriaProductoRequest();
            return ((SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS)(this)).listarCategoriaProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoResponse SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS.obtenerCategoriaProducto(SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoRequest request) {
            return base.Channel.obtenerCategoriaProducto(request);
        }
        
        public SoftProgWeb.CategoriaProductoWS.categoriaProducto obtenerCategoriaProducto(int id) {
            SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoRequest inValue = new SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoRequest();
            inValue.id = id;
            SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoResponse retVal = ((SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS)(this)).obtenerCategoriaProducto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoResponse> SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS.obtenerCategoriaProductoAsync(SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoRequest request) {
            return base.Channel.obtenerCategoriaProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoResponse> obtenerCategoriaProductoAsync(int id) {
            SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoRequest inValue = new SoftProgWeb.CategoriaProductoWS.obtenerCategoriaProductoRequest();
            inValue.id = id;
            return ((SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS)(this)).obtenerCategoriaProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoResponse SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS.eliminarCategoriaProducto(SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoRequest request) {
            return base.Channel.eliminarCategoriaProducto(request);
        }
        
        public void eliminarCategoriaProducto(int id) {
            SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoRequest inValue = new SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoRequest();
            inValue.id = id;
            SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoResponse retVal = ((SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS)(this)).eliminarCategoriaProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoResponse> SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS.eliminarCategoriaProductoAsync(SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoRequest request) {
            return base.Channel.eliminarCategoriaProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoResponse> eliminarCategoriaProductoAsync(int id) {
            SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoRequest inValue = new SoftProgWeb.CategoriaProductoWS.eliminarCategoriaProductoRequest();
            inValue.id = id;
            return ((SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS)(this)).eliminarCategoriaProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoResponse SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS.insertarCategoriaProducto(SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoRequest request) {
            return base.Channel.insertarCategoriaProducto(request);
        }
        
        public void insertarCategoriaProducto(SoftProgWeb.CategoriaProductoWS.categoriaProducto categoriaProducto) {
            SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoRequest inValue = new SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoRequest();
            inValue.categoriaProducto = categoriaProducto;
            SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoResponse retVal = ((SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS)(this)).insertarCategoriaProducto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoResponse> SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS.insertarCategoriaProductoAsync(SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoRequest request) {
            return base.Channel.insertarCategoriaProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoResponse> insertarCategoriaProductoAsync(SoftProgWeb.CategoriaProductoWS.categoriaProducto categoriaProducto) {
            SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoRequest inValue = new SoftProgWeb.CategoriaProductoWS.insertarCategoriaProductoRequest();
            inValue.categoriaProducto = categoriaProducto;
            return ((SoftProgWeb.CategoriaProductoWS.CategoriaProductoWS)(this)).insertarCategoriaProductoAsync(inValue);
        }
    }
}
