//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWeb.ServiceioEmpresaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="ServiceioEmpresaWS.EmpresaWS")]
    public interface EmpresaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasNoActivosRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasNoActivosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosResponse listarEmpresasNoActivos(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasNoActivosRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasNoActivosResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosResponse> listarEmpresasNoActivosAsync(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/eliminarEmpresaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/eliminarEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaResponse eliminarEmpresa(SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/eliminarEmpresaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/eliminarEmpresaResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaResponse> eliminarEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaRequest request);
        
        // CODEGEN: Parameter 'empresa' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/insertarEmpresaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/insertarEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaResponse insertarEmpresa(SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/insertarEmpresaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/insertarEmpresaResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaResponse> insertarEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaRequest request);
        
        // CODEGEN: Parameter 'empresa' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/actualizarEmpresaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/actualizarEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaResponse actualizarEmpresa(SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/actualizarEmpresaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/actualizarEmpresaResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaResponse> actualizarEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasActivosRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasActivosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosResponse listarEmpresasActivos(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasActivosRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasActivosResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosResponse> listarEmpresasActivosAsync(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasPorClienteActivasReq" +
            "uest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasPorClienteActivasRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasResponse listarEmpresasPorClienteActivas(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasPorClienteActivasReq" +
            "uest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasPorClienteActivasRes" +
            "ponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasResponse> listarEmpresasPorClienteActivasAsync(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasPorClientesNoActivas" +
            "Request", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasPorClientesNoActivas" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasResponse listarEmpresasPorClientesNoActivas(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasPorClientesNoActivas" +
            "Request", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasPorClientesNoActivas" +
            "Response")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasResponse> listarEmpresasPorClientesNoActivasAsync(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServiceioEmpresaWS.listarEmpresaResponse listarEmpresa(SoftProgWeb.ServiceioEmpresaWS.listarEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresaResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresaResponse> listarEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.listarEmpresaRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/validarEmpresaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/validarEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServiceioEmpresaWS.validarEmpresaResponse validarEmpresa(SoftProgWeb.ServiceioEmpresaWS.validarEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/validarEmpresaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/validarEmpresaResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.validarEmpresaResponse> validarEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.validarEmpresaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/obtenerEmpresaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/obtenerEmpresaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaResponse obtenerEmpresa(SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/obtenerEmpresaRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/obtenerEmpresaResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaResponse> obtenerEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasPorClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasPorClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteResponse listarEmpresasPorCliente(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasPorClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/EmpresaWS/listarEmpresasPorClienteResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteResponse> listarEmpresasPorClienteAsync(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class empresa : registro {
        
        private cliente clienteField;
        
        private string codigoPostalField;
        
        private string departamentoField;
        
        private string direccionFiscalField;
        
        private string distritoField;
        
        private string emailField;
        
        private string provinciaField;
        
        private string rUCField;
        
        private string razonSocialField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
                this.RaisePropertyChanged("codigoPostal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("departamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccionFiscal {
            get {
                return this.direccionFiscalField;
            }
            set {
                this.direccionFiscalField = value;
                this.RaisePropertyChanged("direccionFiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                this.provinciaField = value;
                this.RaisePropertyChanged("provincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string RUC {
            get {
                return this.rUCField;
            }
            set {
                this.rUCField = value;
                this.RaisePropertyChanged("RUC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("razonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cliente : persona {
        
        private categoriaCliente categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string categoriaClienteField;
        
        private cuentaUsuario cuentaField;
        
        private double lineaCreditoField;
        
        private int numeroPedidosHistoricoField;
        
        private int numeroPedidosMensualProField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaCliente categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string categoriaCliente {
            get {
                return this.categoriaClienteField;
            }
            set {
                this.categoriaClienteField = value;
                this.RaisePropertyChanged("categoriaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public cuentaUsuario cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double lineaCredito {
            get {
                return this.lineaCreditoField;
            }
            set {
                this.lineaCreditoField = value;
                this.RaisePropertyChanged("lineaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroPedidosHistorico {
            get {
                return this.numeroPedidosHistoricoField;
            }
            set {
                this.numeroPedidosHistoricoField = value;
                this.RaisePropertyChanged("numeroPedidosHistorico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int numeroPedidosMensualPro {
            get {
                return this.numeroPedidosMensualProField;
            }
            set {
                this.numeroPedidosMensualProField = value;
                this.RaisePropertyChanged("numeroPedidosMensualPro");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum categoriaCliente {
        
        /// <remarks/>
        DISTRIBUIDOR,
        
        /// <remarks/>
        REVENDEDOR,
        
        /// <remarks/>
        RESTAURANTE,
        
        /// <remarks/>
        HOTEL,
        
        /// <remarks/>
        CATERING,
        
        /// <remarks/>
        GOBIERNO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cuentaUsuario : registro {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cuentaUsuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empresa))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class registro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class localDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class persona : registro {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private localDate fechaNacimientoField;
        
        private genero generoField;
        
        private bool generoFieldSpecified;
        
        private string generoStringField;
        
        private string nombreField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDate fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public genero genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified {
            get {
                return this.generoFieldSpecified;
            }
            set {
                this.generoFieldSpecified = value;
                this.RaisePropertyChanged("generoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string generoString {
            get {
                return this.generoStringField;
            }
            set {
                this.generoStringField = value;
                this.RaisePropertyChanged("generoString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum genero {
        
        /// <remarks/>
        MASCULINO,
        
        /// <remarks/>
        FEMENINO,
        
        /// <remarks/>
        NO_ESPECIFICADO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresasNoActivos", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasNoActivosRequest {
        
        public listarEmpresasNoActivosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresasNoActivosResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasNoActivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioEmpresaWS.empresa[] @return;
        
        public listarEmpresasNoActivosResponse() {
        }
        
        public listarEmpresasNoActivosResponse(SoftProgWeb.ServiceioEmpresaWS.empresa[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpresa", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarEmpresaRequest() {
        }
        
        public eliminarEmpresaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpresaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEmpresaResponse {
        
        public eliminarEmpresaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEmpresa", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioEmpresaWS.empresa empresa;
        
        public insertarEmpresaRequest() {
        }
        
        public insertarEmpresaRequest(SoftProgWeb.ServiceioEmpresaWS.empresa empresa) {
            this.empresa = empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEmpresaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEmpresaResponse {
        
        public insertarEmpresaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEmpresa", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioEmpresaWS.empresa empresa;
        
        public actualizarEmpresaRequest() {
        }
        
        public actualizarEmpresaRequest(SoftProgWeb.ServiceioEmpresaWS.empresa empresa) {
            this.empresa = empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEmpresaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarEmpresaResponse {
        
        public actualizarEmpresaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresasActivos", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasActivosRequest {
        
        public listarEmpresasActivosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresasActivosResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasActivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioEmpresaWS.empresa[] @return;
        
        public listarEmpresasActivosResponse() {
        }
        
        public listarEmpresasActivosResponse(SoftProgWeb.ServiceioEmpresaWS.empresa[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresasPorClienteActivas", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasPorClienteActivasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public listarEmpresasPorClienteActivasRequest() {
        }
        
        public listarEmpresasPorClienteActivasRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresasPorClienteActivasResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasPorClienteActivasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioEmpresaWS.empresa[] @return;
        
        public listarEmpresasPorClienteActivasResponse() {
        }
        
        public listarEmpresasPorClienteActivasResponse(SoftProgWeb.ServiceioEmpresaWS.empresa[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresasPorClientesNoActivas", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasPorClientesNoActivasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public listarEmpresasPorClientesNoActivasRequest() {
        }
        
        public listarEmpresasPorClientesNoActivasRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresasPorClientesNoActivasResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasPorClientesNoActivasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioEmpresaWS.empresa[] @return;
        
        public listarEmpresasPorClientesNoActivasResponse() {
        }
        
        public listarEmpresasPorClientesNoActivasResponse(SoftProgWeb.ServiceioEmpresaWS.empresa[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresa", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresaRequest {
        
        public listarEmpresaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioEmpresaWS.empresa[] @return;
        
        public listarEmpresaResponse() {
        }
        
        public listarEmpresaResponse(SoftProgWeb.ServiceioEmpresaWS.empresa[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarEmpresa", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class validarEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public validarEmpresaRequest() {
        }
        
        public validarEmpresaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarEmpresaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class validarEmpresaResponse {
        
        public validarEmpresaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEmpresa", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerEmpresaRequest() {
        }
        
        public obtenerEmpresaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEmpresaResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioEmpresaWS.empresa @return;
        
        public obtenerEmpresaResponse() {
        }
        
        public obtenerEmpresaResponse(SoftProgWeb.ServiceioEmpresaWS.empresa @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresasPorCliente", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasPorClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public listarEmpresasPorClienteRequest() {
        }
        
        public listarEmpresasPorClienteRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresasPorClienteResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasPorClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServiceioEmpresaWS.empresa[] @return;
        
        public listarEmpresasPorClienteResponse() {
        }
        
        public listarEmpresasPorClienteResponse(SoftProgWeb.ServiceioEmpresaWS.empresa[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpresaWSChannel : SoftProgWeb.ServiceioEmpresaWS.EmpresaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpresaWSClient : System.ServiceModel.ClientBase<SoftProgWeb.ServiceioEmpresaWS.EmpresaWS>, SoftProgWeb.ServiceioEmpresaWS.EmpresaWS {
        
        public EmpresaWSClient() {
        }
        
        public EmpresaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpresaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosResponse SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.listarEmpresasNoActivos(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosRequest request) {
            return base.Channel.listarEmpresasNoActivos(request);
        }
        
        public SoftProgWeb.ServiceioEmpresaWS.empresa[] listarEmpresasNoActivos() {
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosRequest();
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosResponse retVal = ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).listarEmpresasNoActivos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosResponse> SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.listarEmpresasNoActivosAsync(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosRequest request) {
            return base.Channel.listarEmpresasNoActivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosResponse> listarEmpresasNoActivosAsync() {
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.listarEmpresasNoActivosRequest();
            return ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).listarEmpresasNoActivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaResponse SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.eliminarEmpresa(SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaRequest request) {
            return base.Channel.eliminarEmpresa(request);
        }
        
        public void eliminarEmpresa(int id) {
            SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaRequest();
            inValue.id = id;
            SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaResponse retVal = ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).eliminarEmpresa(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaResponse> SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.eliminarEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaRequest request) {
            return base.Channel.eliminarEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaResponse> eliminarEmpresaAsync(int id) {
            SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.eliminarEmpresaRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).eliminarEmpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaResponse SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.insertarEmpresa(SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaRequest request) {
            return base.Channel.insertarEmpresa(request);
        }
        
        public void insertarEmpresa(SoftProgWeb.ServiceioEmpresaWS.empresa empresa) {
            SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaRequest();
            inValue.empresa = empresa;
            SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaResponse retVal = ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).insertarEmpresa(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaResponse> SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.insertarEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaRequest request) {
            return base.Channel.insertarEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaResponse> insertarEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.empresa empresa) {
            SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.insertarEmpresaRequest();
            inValue.empresa = empresa;
            return ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).insertarEmpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaResponse SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.actualizarEmpresa(SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaRequest request) {
            return base.Channel.actualizarEmpresa(request);
        }
        
        public void actualizarEmpresa(SoftProgWeb.ServiceioEmpresaWS.empresa empresa) {
            SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaRequest();
            inValue.empresa = empresa;
            SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaResponse retVal = ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).actualizarEmpresa(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaResponse> SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.actualizarEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaRequest request) {
            return base.Channel.actualizarEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaResponse> actualizarEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.empresa empresa) {
            SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.actualizarEmpresaRequest();
            inValue.empresa = empresa;
            return ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).actualizarEmpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosResponse SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.listarEmpresasActivos(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosRequest request) {
            return base.Channel.listarEmpresasActivos(request);
        }
        
        public SoftProgWeb.ServiceioEmpresaWS.empresa[] listarEmpresasActivos() {
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosRequest();
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosResponse retVal = ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).listarEmpresasActivos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosResponse> SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.listarEmpresasActivosAsync(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosRequest request) {
            return base.Channel.listarEmpresasActivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosResponse> listarEmpresasActivosAsync() {
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.listarEmpresasActivosRequest();
            return ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).listarEmpresasActivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasResponse SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.listarEmpresasPorClienteActivas(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasRequest request) {
            return base.Channel.listarEmpresasPorClienteActivas(request);
        }
        
        public SoftProgWeb.ServiceioEmpresaWS.empresa[] listarEmpresasPorClienteActivas(int id) {
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasRequest();
            inValue.id = id;
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasResponse retVal = ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).listarEmpresasPorClienteActivas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasResponse> SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.listarEmpresasPorClienteActivasAsync(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasRequest request) {
            return base.Channel.listarEmpresasPorClienteActivasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasResponse> listarEmpresasPorClienteActivasAsync(int id) {
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteActivasRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).listarEmpresasPorClienteActivasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasResponse SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.listarEmpresasPorClientesNoActivas(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasRequest request) {
            return base.Channel.listarEmpresasPorClientesNoActivas(request);
        }
        
        public SoftProgWeb.ServiceioEmpresaWS.empresa[] listarEmpresasPorClientesNoActivas(int id) {
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasRequest();
            inValue.id = id;
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasResponse retVal = ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).listarEmpresasPorClientesNoActivas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasResponse> SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.listarEmpresasPorClientesNoActivasAsync(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasRequest request) {
            return base.Channel.listarEmpresasPorClientesNoActivasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasResponse> listarEmpresasPorClientesNoActivasAsync(int id) {
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClientesNoActivasRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).listarEmpresasPorClientesNoActivasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioEmpresaWS.listarEmpresaResponse SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.listarEmpresa(SoftProgWeb.ServiceioEmpresaWS.listarEmpresaRequest request) {
            return base.Channel.listarEmpresa(request);
        }
        
        public SoftProgWeb.ServiceioEmpresaWS.empresa[] listarEmpresa() {
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresaRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.listarEmpresaRequest();
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresaResponse retVal = ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).listarEmpresa(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresaResponse> SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.listarEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.listarEmpresaRequest request) {
            return base.Channel.listarEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresaResponse> listarEmpresaAsync() {
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresaRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.listarEmpresaRequest();
            return ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).listarEmpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioEmpresaWS.validarEmpresaResponse SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.validarEmpresa(SoftProgWeb.ServiceioEmpresaWS.validarEmpresaRequest request) {
            return base.Channel.validarEmpresa(request);
        }
        
        public void validarEmpresa(int id) {
            SoftProgWeb.ServiceioEmpresaWS.validarEmpresaRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.validarEmpresaRequest();
            inValue.id = id;
            SoftProgWeb.ServiceioEmpresaWS.validarEmpresaResponse retVal = ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).validarEmpresa(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.validarEmpresaResponse> SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.validarEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.validarEmpresaRequest request) {
            return base.Channel.validarEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.validarEmpresaResponse> validarEmpresaAsync(int id) {
            SoftProgWeb.ServiceioEmpresaWS.validarEmpresaRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.validarEmpresaRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).validarEmpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaResponse SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.obtenerEmpresa(SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaRequest request) {
            return base.Channel.obtenerEmpresa(request);
        }
        
        public SoftProgWeb.ServiceioEmpresaWS.empresa obtenerEmpresa(int id) {
            SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaRequest();
            inValue.id = id;
            SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaResponse retVal = ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).obtenerEmpresa(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaResponse> SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.obtenerEmpresaAsync(SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaRequest request) {
            return base.Channel.obtenerEmpresaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaResponse> obtenerEmpresaAsync(int id) {
            SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.obtenerEmpresaRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).obtenerEmpresaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteResponse SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.listarEmpresasPorCliente(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteRequest request) {
            return base.Channel.listarEmpresasPorCliente(request);
        }
        
        public SoftProgWeb.ServiceioEmpresaWS.empresa[] listarEmpresasPorCliente(int id) {
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteRequest();
            inValue.id = id;
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteResponse retVal = ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).listarEmpresasPorCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteResponse> SoftProgWeb.ServiceioEmpresaWS.EmpresaWS.listarEmpresasPorClienteAsync(SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteRequest request) {
            return base.Channel.listarEmpresasPorClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteResponse> listarEmpresasPorClienteAsync(int id) {
            SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteRequest inValue = new SoftProgWeb.ServiceioEmpresaWS.listarEmpresasPorClienteRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServiceioEmpresaWS.EmpresaWS)(this)).listarEmpresasPorClienteAsync(inValue);
        }
    }
}
