//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWeb.ServicioClienteWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class localDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cuentaUsuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class registro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cuentaUsuario : registro {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class persona : registro {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private localDate fechaNacimientoField;
        
        private genero generoField;
        
        private bool generoFieldSpecified;
        
        private string generoStringField;
        
        private string nombreField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localDate fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public genero genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified {
            get {
                return this.generoFieldSpecified;
            }
            set {
                this.generoFieldSpecified = value;
                this.RaisePropertyChanged("generoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string generoString {
            get {
                return this.generoStringField;
            }
            set {
                this.generoStringField = value;
                this.RaisePropertyChanged("generoString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum genero {
        
        /// <remarks/>
        MASCULINO,
        
        /// <remarks/>
        FEMENINO,
        
        /// <remarks/>
        NO_ESPECIFICADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cliente : persona {
        
        private categoriaCliente categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string categoriaClienteField;
        
        private cuentaUsuario cuentaField;
        
        private double lineaCreditoField;
        
        private int numeroPedidosHistoricoField;
        
        private int numeroPedidosMensualProField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaCliente categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string categoriaCliente {
            get {
                return this.categoriaClienteField;
            }
            set {
                this.categoriaClienteField = value;
                this.RaisePropertyChanged("categoriaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public cuentaUsuario cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double lineaCredito {
            get {
                return this.lineaCreditoField;
            }
            set {
                this.lineaCreditoField = value;
                this.RaisePropertyChanged("lineaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroPedidosHistorico {
            get {
                return this.numeroPedidosHistoricoField;
            }
            set {
                this.numeroPedidosHistoricoField = value;
                this.RaisePropertyChanged("numeroPedidosHistorico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int numeroPedidosMensualPro {
            get {
                return this.numeroPedidosMensualProField;
            }
            set {
                this.numeroPedidosMensualProField = value;
                this.RaisePropertyChanged("numeroPedidosMensualPro");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum categoriaCliente {
        
        /// <remarks/>
        DISTRIBUIDOR,
        
        /// <remarks/>
        REVENDEDOR,
        
        /// <remarks/>
        RESTAURANTE,
        
        /// <remarks/>
        HOTEL,
        
        /// <remarks/>
        CATERING,
        
        /// <remarks/>
        GOBIERNO,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="ServicioClienteWS.ClienteWS")]
    public interface ClienteWS {
        
        // CODEGEN: Parameter 'cliente' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClienteWS/insertarClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClienteWS/insertarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServicioClienteWS.insertarClienteResponse insertarCliente(SoftProgWeb.ServicioClienteWS.insertarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClienteWS/insertarClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClienteWS/insertarClienteResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.insertarClienteResponse> insertarClienteAsync(SoftProgWeb.ServicioClienteWS.insertarClienteRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClienteWS/eEliminarClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClienteWS/eEliminarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServicioClienteWS.eEliminarClienteResponse eEliminarCliente(SoftProgWeb.ServicioClienteWS.eEliminarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClienteWS/eEliminarClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClienteWS/eEliminarClienteResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.eEliminarClienteResponse> eEliminarClienteAsync(SoftProgWeb.ServicioClienteWS.eEliminarClienteRequest request);
        
        // CODEGEN: Parameter 'cliente' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClienteWS/actualizarClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClienteWS/actualizarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServicioClienteWS.actualizarClienteResponse actualizarCliente(SoftProgWeb.ServicioClienteWS.actualizarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClienteWS/actualizarClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClienteWS/actualizarClienteResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.actualizarClienteResponse> actualizarClienteAsync(SoftProgWeb.ServicioClienteWS.actualizarClienteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClienteWS/listarClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClienteWS/listarClienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftProgWeb.ServicioClienteWS.Exception), Action="http://services.softprog.pucp.edu.pe/ClienteWS/listarCliente/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServicioClienteWS.listarClienteResponse listarCliente(SoftProgWeb.ServicioClienteWS.listarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClienteWS/listarClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClienteWS/listarClienteResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.listarClienteResponse> listarClienteAsync(SoftProgWeb.ServicioClienteWS.listarClienteRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClienteWS/buscarPorDniRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClienteWS/buscarPorDniResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServicioClienteWS.buscarPorDniResponse buscarPorDni(SoftProgWeb.ServicioClienteWS.buscarPorDniRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClienteWS/buscarPorDniRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClienteWS/buscarPorDniResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.buscarPorDniResponse> buscarPorDniAsync(SoftProgWeb.ServicioClienteWS.buscarPorDniRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClienteWS/obtenerClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClienteWS/obtenerClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServicioClienteWS.obtenerClienteResponse obtenerCliente(SoftProgWeb.ServicioClienteWS.obtenerClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/ClienteWS/obtenerClienteRequest", ReplyAction="http://services.softprog.pucp.edu.pe/ClienteWS/obtenerClienteResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.obtenerClienteResponse> obtenerClienteAsync(SoftProgWeb.ServicioClienteWS.obtenerClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCliente", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioClienteWS.cliente cliente;
        
        public insertarClienteRequest() {
        }
        
        public insertarClienteRequest(SoftProgWeb.ServicioClienteWS.cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarClienteResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarClienteResponse {
        
        public insertarClienteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eEliminarCliente", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eEliminarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eEliminarClienteRequest() {
        }
        
        public eEliminarClienteRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eEliminarClienteResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eEliminarClienteResponse {
        
        public eEliminarClienteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarCliente", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioClienteWS.cliente cliente;
        
        public actualizarClienteRequest() {
        }
        
        public actualizarClienteRequest(SoftProgWeb.ServicioClienteWS.cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarClienteResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarClienteResponse {
        
        public actualizarClienteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCliente", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarClienteRequest {
        
        public listarClienteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarClienteResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioClienteWS.cliente[] @return;
        
        public listarClienteResponse() {
        }
        
        public listarClienteResponse(SoftProgWeb.ServicioClienteWS.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPorDni", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarPorDniRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        public buscarPorDniRequest() {
        }
        
        public buscarPorDniRequest(string dni) {
            this.dni = dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPorDniResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarPorDniResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioClienteWS.cliente @return;
        
        public buscarPorDniResponse() {
        }
        
        public buscarPorDniResponse(SoftProgWeb.ServicioClienteWS.cliente @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCliente", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerClienteRequest() {
        }
        
        public obtenerClienteRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerClienteResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioClienteWS.cliente @return;
        
        public obtenerClienteResponse() {
        }
        
        public obtenerClienteResponse(SoftProgWeb.ServicioClienteWS.cliente @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClienteWSChannel : SoftProgWeb.ServicioClienteWS.ClienteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteWSClient : System.ServiceModel.ClientBase<SoftProgWeb.ServicioClienteWS.ClienteWS>, SoftProgWeb.ServicioClienteWS.ClienteWS {
        
        public ClienteWSClient() {
        }
        
        public ClienteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioClienteWS.insertarClienteResponse SoftProgWeb.ServicioClienteWS.ClienteWS.insertarCliente(SoftProgWeb.ServicioClienteWS.insertarClienteRequest request) {
            return base.Channel.insertarCliente(request);
        }
        
        public void insertarCliente(SoftProgWeb.ServicioClienteWS.cliente cliente) {
            SoftProgWeb.ServicioClienteWS.insertarClienteRequest inValue = new SoftProgWeb.ServicioClienteWS.insertarClienteRequest();
            inValue.cliente = cliente;
            SoftProgWeb.ServicioClienteWS.insertarClienteResponse retVal = ((SoftProgWeb.ServicioClienteWS.ClienteWS)(this)).insertarCliente(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.insertarClienteResponse> SoftProgWeb.ServicioClienteWS.ClienteWS.insertarClienteAsync(SoftProgWeb.ServicioClienteWS.insertarClienteRequest request) {
            return base.Channel.insertarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.insertarClienteResponse> insertarClienteAsync(SoftProgWeb.ServicioClienteWS.cliente cliente) {
            SoftProgWeb.ServicioClienteWS.insertarClienteRequest inValue = new SoftProgWeb.ServicioClienteWS.insertarClienteRequest();
            inValue.cliente = cliente;
            return ((SoftProgWeb.ServicioClienteWS.ClienteWS)(this)).insertarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioClienteWS.eEliminarClienteResponse SoftProgWeb.ServicioClienteWS.ClienteWS.eEliminarCliente(SoftProgWeb.ServicioClienteWS.eEliminarClienteRequest request) {
            return base.Channel.eEliminarCliente(request);
        }
        
        public void eEliminarCliente(int id) {
            SoftProgWeb.ServicioClienteWS.eEliminarClienteRequest inValue = new SoftProgWeb.ServicioClienteWS.eEliminarClienteRequest();
            inValue.id = id;
            SoftProgWeb.ServicioClienteWS.eEliminarClienteResponse retVal = ((SoftProgWeb.ServicioClienteWS.ClienteWS)(this)).eEliminarCliente(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.eEliminarClienteResponse> SoftProgWeb.ServicioClienteWS.ClienteWS.eEliminarClienteAsync(SoftProgWeb.ServicioClienteWS.eEliminarClienteRequest request) {
            return base.Channel.eEliminarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.eEliminarClienteResponse> eEliminarClienteAsync(int id) {
            SoftProgWeb.ServicioClienteWS.eEliminarClienteRequest inValue = new SoftProgWeb.ServicioClienteWS.eEliminarClienteRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServicioClienteWS.ClienteWS)(this)).eEliminarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioClienteWS.actualizarClienteResponse SoftProgWeb.ServicioClienteWS.ClienteWS.actualizarCliente(SoftProgWeb.ServicioClienteWS.actualizarClienteRequest request) {
            return base.Channel.actualizarCliente(request);
        }
        
        public void actualizarCliente(SoftProgWeb.ServicioClienteWS.cliente cliente) {
            SoftProgWeb.ServicioClienteWS.actualizarClienteRequest inValue = new SoftProgWeb.ServicioClienteWS.actualizarClienteRequest();
            inValue.cliente = cliente;
            SoftProgWeb.ServicioClienteWS.actualizarClienteResponse retVal = ((SoftProgWeb.ServicioClienteWS.ClienteWS)(this)).actualizarCliente(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.actualizarClienteResponse> SoftProgWeb.ServicioClienteWS.ClienteWS.actualizarClienteAsync(SoftProgWeb.ServicioClienteWS.actualizarClienteRequest request) {
            return base.Channel.actualizarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.actualizarClienteResponse> actualizarClienteAsync(SoftProgWeb.ServicioClienteWS.cliente cliente) {
            SoftProgWeb.ServicioClienteWS.actualizarClienteRequest inValue = new SoftProgWeb.ServicioClienteWS.actualizarClienteRequest();
            inValue.cliente = cliente;
            return ((SoftProgWeb.ServicioClienteWS.ClienteWS)(this)).actualizarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioClienteWS.listarClienteResponse SoftProgWeb.ServicioClienteWS.ClienteWS.listarCliente(SoftProgWeb.ServicioClienteWS.listarClienteRequest request) {
            return base.Channel.listarCliente(request);
        }
        
        public SoftProgWeb.ServicioClienteWS.cliente[] listarCliente() {
            SoftProgWeb.ServicioClienteWS.listarClienteRequest inValue = new SoftProgWeb.ServicioClienteWS.listarClienteRequest();
            SoftProgWeb.ServicioClienteWS.listarClienteResponse retVal = ((SoftProgWeb.ServicioClienteWS.ClienteWS)(this)).listarCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.listarClienteResponse> SoftProgWeb.ServicioClienteWS.ClienteWS.listarClienteAsync(SoftProgWeb.ServicioClienteWS.listarClienteRequest request) {
            return base.Channel.listarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.listarClienteResponse> listarClienteAsync() {
            SoftProgWeb.ServicioClienteWS.listarClienteRequest inValue = new SoftProgWeb.ServicioClienteWS.listarClienteRequest();
            return ((SoftProgWeb.ServicioClienteWS.ClienteWS)(this)).listarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioClienteWS.buscarPorDniResponse SoftProgWeb.ServicioClienteWS.ClienteWS.buscarPorDni(SoftProgWeb.ServicioClienteWS.buscarPorDniRequest request) {
            return base.Channel.buscarPorDni(request);
        }
        
        public SoftProgWeb.ServicioClienteWS.cliente buscarPorDni(string dni) {
            SoftProgWeb.ServicioClienteWS.buscarPorDniRequest inValue = new SoftProgWeb.ServicioClienteWS.buscarPorDniRequest();
            inValue.dni = dni;
            SoftProgWeb.ServicioClienteWS.buscarPorDniResponse retVal = ((SoftProgWeb.ServicioClienteWS.ClienteWS)(this)).buscarPorDni(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.buscarPorDniResponse> SoftProgWeb.ServicioClienteWS.ClienteWS.buscarPorDniAsync(SoftProgWeb.ServicioClienteWS.buscarPorDniRequest request) {
            return base.Channel.buscarPorDniAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.buscarPorDniResponse> buscarPorDniAsync(string dni) {
            SoftProgWeb.ServicioClienteWS.buscarPorDniRequest inValue = new SoftProgWeb.ServicioClienteWS.buscarPorDniRequest();
            inValue.dni = dni;
            return ((SoftProgWeb.ServicioClienteWS.ClienteWS)(this)).buscarPorDniAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioClienteWS.obtenerClienteResponse SoftProgWeb.ServicioClienteWS.ClienteWS.obtenerCliente(SoftProgWeb.ServicioClienteWS.obtenerClienteRequest request) {
            return base.Channel.obtenerCliente(request);
        }
        
        public SoftProgWeb.ServicioClienteWS.cliente obtenerCliente(int id) {
            SoftProgWeb.ServicioClienteWS.obtenerClienteRequest inValue = new SoftProgWeb.ServicioClienteWS.obtenerClienteRequest();
            inValue.id = id;
            SoftProgWeb.ServicioClienteWS.obtenerClienteResponse retVal = ((SoftProgWeb.ServicioClienteWS.ClienteWS)(this)).obtenerCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.obtenerClienteResponse> SoftProgWeb.ServicioClienteWS.ClienteWS.obtenerClienteAsync(SoftProgWeb.ServicioClienteWS.obtenerClienteRequest request) {
            return base.Channel.obtenerClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioClienteWS.obtenerClienteResponse> obtenerClienteAsync(int id) {
            SoftProgWeb.ServicioClienteWS.obtenerClienteRequest inValue = new SoftProgWeb.ServicioClienteWS.obtenerClienteRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServicioClienteWS.ClienteWS)(this)).obtenerClienteAsync(inValue);
        }
    }
}
