//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProgWeb.ServicioOrdenCompraWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softprog.pucp.edu.pe/", ConfigurationName="ServicioOrdenCompraWS.OrdenCompraWS")]
    public interface OrdenCompraWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenCompraWS/obtenerOrdenCompraRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenCompraWS/obtenerOrdenCompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraResponse obtenerOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenCompraWS/obtenerOrdenCompraRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenCompraWS/obtenerOrdenCompraResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraResponse> obtenerOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraRequest request);
        
        // CODEGEN: Parameter 'ordenCompra' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenCompraWS/insertarOrdenCompraRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenCompraWS/insertarOrdenCompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraResponse insertarOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenCompraWS/insertarOrdenCompraRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenCompraWS/insertarOrdenCompraResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraResponse> insertarOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraRequest request);
        
        // CODEGEN: Parameter 'ordenCompra' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenCompraWS/actualizarOrdenCompraRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenCompraWS/actualizarOrdenCompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraResponse actualizarOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenCompraWS/actualizarOrdenCompraRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenCompraWS/actualizarOrdenCompraResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraResponse> actualizarOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenCompraWS/listarOrdenCompraRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenCompraWS/listarOrdenCompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraResponse listarOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenCompraWS/listarOrdenCompraRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenCompraWS/listarOrdenCompraResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraResponse> listarOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenCompraWS/desactivarOrdenCompraRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenCompraWS/desactivarOrdenCompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraResponse desactivarOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenCompraWS/desactivarOrdenCompraRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenCompraWS/desactivarOrdenCompraResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraResponse> desactivarOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraRequest request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenCompraWS/eliminarOrdenCompraRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenCompraWS/eliminarOrdenCompraResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(registro))]
        SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraResponse eliminarOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softprog.pucp.edu.pe/OrdenCompraWS/eliminarOrdenCompraRequest", ReplyAction="http://services.softprog.pucp.edu.pe/OrdenCompraWS/eliminarOrdenCompraResponse")]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraResponse> eliminarOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class ordenCompra : registro {
        
        private cliente clienteField;
        
        private double descuentoTotalField;
        
        private detalleEnvio detalleEnvioField;
        
        private estadoOrdenCompra estadoField;
        
        private bool estadoFieldSpecified;
        
        private string estadoStringField;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private lineaOrdenCompra[] lineasOrdenField;
        
        private double totalFinalField;
        
        private double totalParcialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double descuentoTotal {
            get {
                return this.descuentoTotalField;
            }
            set {
                this.descuentoTotalField = value;
                this.RaisePropertyChanged("descuentoTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public detalleEnvio detalleEnvio {
            get {
                return this.detalleEnvioField;
            }
            set {
                this.detalleEnvioField = value;
                this.RaisePropertyChanged("detalleEnvio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public estadoOrdenCompra estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string estadoString {
            get {
                return this.estadoStringField;
            }
            set {
                this.estadoStringField = value;
                this.RaisePropertyChanged("estadoString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineasOrden", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public lineaOrdenCompra[] lineasOrden {
            get {
                return this.lineasOrdenField;
            }
            set {
                this.lineasOrdenField = value;
                this.RaisePropertyChanged("lineasOrden");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double totalFinal {
            get {
                return this.totalFinalField;
            }
            set {
                this.totalFinalField = value;
                this.RaisePropertyChanged("totalFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double totalParcial {
            get {
                return this.totalParcialField;
            }
            set {
                this.totalParcialField = value;
                this.RaisePropertyChanged("totalParcial");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class cliente : persona {
        
        private categoriaCliente categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private string categoriaClienteField;
        
        private double lineaCreditoField;
        
        private int numeroPedidosHistoricoField;
        
        private int numeroPedidosMensualProField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaCliente categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string categoriaCliente {
            get {
                return this.categoriaClienteField;
            }
            set {
                this.categoriaClienteField = value;
                this.RaisePropertyChanged("categoriaCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double lineaCredito {
            get {
                return this.lineaCreditoField;
            }
            set {
                this.lineaCreditoField = value;
                this.RaisePropertyChanged("lineaCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int numeroPedidosHistorico {
            get {
                return this.numeroPedidosHistoricoField;
            }
            set {
                this.numeroPedidosHistoricoField = value;
                this.RaisePropertyChanged("numeroPedidosHistorico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroPedidosMensualPro {
            get {
                return this.numeroPedidosMensualProField;
            }
            set {
                this.numeroPedidosMensualProField = value;
                this.RaisePropertyChanged("numeroPedidosMensualPro");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum categoriaCliente {
        
        /// <remarks/>
        DISTRIBUIDOR,
        
        /// <remarks/>
        REVENDEDOR,
        
        /// <remarks/>
        RESTAURANTE,
        
        /// <remarks/>
        HOTEL,
        
        /// <remarks/>
        CATERING,
        
        /// <remarks/>
        GOBIERNO,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class persona : registro {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private genero generoField;
        
        private bool generoFieldSpecified;
        
        private string generoStringField;
        
        private string nombreField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public genero genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified {
            get {
                return this.generoFieldSpecified;
            }
            set {
                this.generoFieldSpecified = value;
                this.RaisePropertyChanged("generoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string generoString {
            get {
                return this.generoStringField;
            }
            set {
                this.generoStringField = value;
                this.RaisePropertyChanged("generoString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum genero {
        
        /// <remarks/>
        HOMBRE,
        
        /// <remarks/>
        MUJER,
        
        /// <remarks/>
        NO_ESPECIFICADO,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(categoriaProducto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(producto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(carritoCompras))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lineaOrdenCompra))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(detalleEnvio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(persona))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ordenCompra))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class registro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class categoriaProducto : registro {
        
        private categoriaProducto categoriaPadreField;
        
        private string descripcionField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaProducto categoriaPadre {
            get {
                return this.categoriaPadreField;
            }
            set {
                this.categoriaPadreField = value;
                this.RaisePropertyChanged("categoriaPadre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class producto : registro {
        
        private categoriaProducto categoriaField;
        
        private string descripcionField;
        
        private string marcaField;
        
        private unidadMedida medidaAlMayorField;
        
        private bool medidaAlMayorFieldSpecified;
        
        private string medidaAlMayorStringField;
        
        private string nombreField;
        
        private double precioAlMayorField;
        
        private double precioUnitarioField;
        
        private string sKUField;
        
        private int stockDisponibleField;
        
        private int stockMaximoField;
        
        private int stockMinimoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public categoriaProducto categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public unidadMedida medidaAlMayor {
            get {
                return this.medidaAlMayorField;
            }
            set {
                this.medidaAlMayorField = value;
                this.RaisePropertyChanged("medidaAlMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool medidaAlMayorSpecified {
            get {
                return this.medidaAlMayorFieldSpecified;
            }
            set {
                this.medidaAlMayorFieldSpecified = value;
                this.RaisePropertyChanged("medidaAlMayorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string medidaAlMayorString {
            get {
                return this.medidaAlMayorStringField;
            }
            set {
                this.medidaAlMayorStringField = value;
                this.RaisePropertyChanged("medidaAlMayorString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double precioAlMayor {
            get {
                return this.precioAlMayorField;
            }
            set {
                this.precioAlMayorField = value;
                this.RaisePropertyChanged("precioAlMayor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
                this.RaisePropertyChanged("SKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int stockDisponible {
            get {
                return this.stockDisponibleField;
            }
            set {
                this.stockDisponibleField = value;
                this.RaisePropertyChanged("stockDisponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int stockMaximo {
            get {
                return this.stockMaximoField;
            }
            set {
                this.stockMaximoField = value;
                this.RaisePropertyChanged("stockMaximo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int stockMinimo {
            get {
                return this.stockMinimoField;
            }
            set {
                this.stockMinimoField = value;
                this.RaisePropertyChanged("stockMinimo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum unidadMedida {
        
        /// <remarks/>
        KILOGRAMO,
        
        /// <remarks/>
        LITRO,
        
        /// <remarks/>
        GALON,
        
        /// <remarks/>
        BOTELLA,
        
        /// <remarks/>
        CAJA,
        
        /// <remarks/>
        PAQUETE,
        
        /// <remarks/>
        SACO,
        
        /// <remarks/>
        PACK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class carritoCompras : registro {
        
        private cliente clienteField;
        
        private estadoCarrito estadoField;
        
        private bool estadoFieldSpecified;
        
        private string estadoStringField;
        
        private double totalConDescuentoField;
        
        private double totalParcialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public cliente cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoCarrito estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string estadoString {
            get {
                return this.estadoStringField;
            }
            set {
                this.estadoStringField = value;
                this.RaisePropertyChanged("estadoString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double totalConDescuento {
            get {
                return this.totalConDescuentoField;
            }
            set {
                this.totalConDescuentoField = value;
                this.RaisePropertyChanged("totalConDescuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double totalParcial {
            get {
                return this.totalParcialField;
            }
            set {
                this.totalParcialField = value;
                this.RaisePropertyChanged("totalParcial");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum estadoCarrito {
        
        /// <remarks/>
        VACIO,
        
        /// <remarks/>
        EN_PROCESO,
        
        /// <remarks/>
        EN_REVISION,
        
        /// <remarks/>
        CONFIRMADO,
        
        /// <remarks/>
        CANCELADO,
        
        /// <remarks/>
        EXPIRADO,
        
        /// <remarks/>
        COMPLETADO,
        
        /// <remarks/>
        PENDIENTE,
        
        /// <remarks/>
        PROCESADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class lineaOrdenCompra : registro {
        
        private int cantidadField;
        
        private carritoCompras carritoComprasField;
        
        private int codigoField;
        
        private double montoPagadoField;
        
        private ordenCompra ordenCompraField;
        
        private double precioUnitarioField;
        
        private producto productoField;
        
        private double subTotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public carritoCompras carritoCompras {
            get {
                return this.carritoComprasField;
            }
            set {
                this.carritoComprasField = value;
                this.RaisePropertyChanged("carritoCompras");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double montoPagado {
            get {
                return this.montoPagadoField;
            }
            set {
                this.montoPagadoField = value;
                this.RaisePropertyChanged("montoPagado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ordenCompra ordenCompra {
            get {
                return this.ordenCompraField;
            }
            set {
                this.ordenCompraField = value;
                this.RaisePropertyChanged("ordenCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double subTotal {
            get {
                return this.subTotalField;
            }
            set {
                this.subTotalField = value;
                this.RaisePropertyChanged("subTotal");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public partial class detalleEnvio : registro {
        
        private string descripcionField;
        
        private string direccionField;
        
        private distrito distritoField;
        
        private bool distritoFieldSpecified;
        
        private string distritoStringField;
        
        private System.DateTime fechaEntregaField;
        
        private bool fechaEntregaFieldSpecified;
        
        private System.DateTime horarioEntregaField;
        
        private bool horarioEntregaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public distrito distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distritoSpecified {
            get {
                return this.distritoFieldSpecified;
            }
            set {
                this.distritoFieldSpecified = value;
                this.RaisePropertyChanged("distritoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string distritoString {
            get {
                return this.distritoStringField;
            }
            set {
                this.distritoStringField = value;
                this.RaisePropertyChanged("distritoString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaEntrega {
            get {
                return this.fechaEntregaField;
            }
            set {
                this.fechaEntregaField = value;
                this.RaisePropertyChanged("fechaEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEntregaSpecified {
            get {
                return this.fechaEntregaFieldSpecified;
            }
            set {
                this.fechaEntregaFieldSpecified = value;
                this.RaisePropertyChanged("fechaEntregaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime horarioEntrega {
            get {
                return this.horarioEntregaField;
            }
            set {
                this.horarioEntregaField = value;
                this.RaisePropertyChanged("horarioEntrega");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horarioEntregaSpecified {
            get {
                return this.horarioEntregaFieldSpecified;
            }
            set {
                this.horarioEntregaFieldSpecified = value;
                this.RaisePropertyChanged("horarioEntregaSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum distrito {
        
        /// <remarks/>
        PUEBLO_LIBRE,
        
        /// <remarks/>
        SAN_MIGUEL,
        
        /// <remarks/>
        SAN_BORJA,
        
        /// <remarks/>
        SAN_LUIS,
        
        /// <remarks/>
        LINCE,
        
        /// <remarks/>
        CALLAO,
        
        /// <remarks/>
        LA_VICTORIA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softprog.pucp.edu.pe/")]
    public enum estadoOrdenCompra {
        
        /// <remarks/>
        PAGADO,
        
        /// <remarks/>
        EN_PREPARACION,
        
        /// <remarks/>
        ENVIADO,
        
        /// <remarks/>
        ENTREGADO,
        
        /// <remarks/>
        CANCELADO,
        
        /// <remarks/>
        REEMBOLSADO,
        
        /// <remarks/>
        EXPIRADO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerOrdenCompra", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerOrdenCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerOrdenCompraRequest() {
        }
        
        public obtenerOrdenCompraRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerOrdenCompraResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerOrdenCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioOrdenCompraWS.ordenCompra @return;
        
        public obtenerOrdenCompraResponse() {
        }
        
        public obtenerOrdenCompraResponse(SoftProgWeb.ServicioOrdenCompraWS.ordenCompra @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOrdenCompra", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarOrdenCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioOrdenCompraWS.ordenCompra ordenCompra;
        
        public insertarOrdenCompraRequest() {
        }
        
        public insertarOrdenCompraRequest(SoftProgWeb.ServicioOrdenCompraWS.ordenCompra ordenCompra) {
            this.ordenCompra = ordenCompra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOrdenCompraResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarOrdenCompraResponse {
        
        public insertarOrdenCompraResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarOrdenCompra", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarOrdenCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioOrdenCompraWS.ordenCompra ordenCompra;
        
        public actualizarOrdenCompraRequest() {
        }
        
        public actualizarOrdenCompraRequest(SoftProgWeb.ServicioOrdenCompraWS.ordenCompra ordenCompra) {
            this.ordenCompra = ordenCompra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarOrdenCompraResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarOrdenCompraResponse {
        
        public actualizarOrdenCompraResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenCompra", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenCompraRequest {
        
        public listarOrdenCompraRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenCompraResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenCompraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProgWeb.ServicioOrdenCompraWS.ordenCompra[] @return;
        
        public listarOrdenCompraResponse() {
        }
        
        public listarOrdenCompraResponse(SoftProgWeb.ServicioOrdenCompraWS.ordenCompra[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="desactivarOrdenCompra", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class desactivarOrdenCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public desactivarOrdenCompraRequest() {
        }
        
        public desactivarOrdenCompraRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="desactivarOrdenCompraResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class desactivarOrdenCompraResponse {
        
        public desactivarOrdenCompraResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenCompra", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOrdenCompraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softprog.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarOrdenCompraRequest() {
        }
        
        public eliminarOrdenCompraRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenCompraResponse", WrapperNamespace="http://services.softprog.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOrdenCompraResponse {
        
        public eliminarOrdenCompraResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdenCompraWSChannel : SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenCompraWSClient : System.ServiceModel.ClientBase<SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS>, SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS {
        
        public OrdenCompraWSClient() {
        }
        
        public OrdenCompraWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenCompraWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenCompraWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenCompraWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraResponse SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS.obtenerOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraRequest request) {
            return base.Channel.obtenerOrdenCompra(request);
        }
        
        public SoftProgWeb.ServicioOrdenCompraWS.ordenCompra obtenerOrdenCompra(int id) {
            SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraRequest inValue = new SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraRequest();
            inValue.id = id;
            SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraResponse retVal = ((SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS)(this)).obtenerOrdenCompra(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraResponse> SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS.obtenerOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraRequest request) {
            return base.Channel.obtenerOrdenCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraResponse> obtenerOrdenCompraAsync(int id) {
            SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraRequest inValue = new SoftProgWeb.ServicioOrdenCompraWS.obtenerOrdenCompraRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS)(this)).obtenerOrdenCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraResponse SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS.insertarOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraRequest request) {
            return base.Channel.insertarOrdenCompra(request);
        }
        
        public void insertarOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.ordenCompra ordenCompra) {
            SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraRequest inValue = new SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraRequest();
            inValue.ordenCompra = ordenCompra;
            SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraResponse retVal = ((SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS)(this)).insertarOrdenCompra(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraResponse> SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS.insertarOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraRequest request) {
            return base.Channel.insertarOrdenCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraResponse> insertarOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.ordenCompra ordenCompra) {
            SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraRequest inValue = new SoftProgWeb.ServicioOrdenCompraWS.insertarOrdenCompraRequest();
            inValue.ordenCompra = ordenCompra;
            return ((SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS)(this)).insertarOrdenCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraResponse SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS.actualizarOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraRequest request) {
            return base.Channel.actualizarOrdenCompra(request);
        }
        
        public void actualizarOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.ordenCompra ordenCompra) {
            SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraRequest inValue = new SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraRequest();
            inValue.ordenCompra = ordenCompra;
            SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraResponse retVal = ((SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS)(this)).actualizarOrdenCompra(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraResponse> SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS.actualizarOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraRequest request) {
            return base.Channel.actualizarOrdenCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraResponse> actualizarOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.ordenCompra ordenCompra) {
            SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraRequest inValue = new SoftProgWeb.ServicioOrdenCompraWS.actualizarOrdenCompraRequest();
            inValue.ordenCompra = ordenCompra;
            return ((SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS)(this)).actualizarOrdenCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraResponse SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS.listarOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraRequest request) {
            return base.Channel.listarOrdenCompra(request);
        }
        
        public SoftProgWeb.ServicioOrdenCompraWS.ordenCompra[] listarOrdenCompra() {
            SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraRequest inValue = new SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraRequest();
            SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraResponse retVal = ((SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS)(this)).listarOrdenCompra(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraResponse> SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS.listarOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraRequest request) {
            return base.Channel.listarOrdenCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraResponse> listarOrdenCompraAsync() {
            SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraRequest inValue = new SoftProgWeb.ServicioOrdenCompraWS.listarOrdenCompraRequest();
            return ((SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS)(this)).listarOrdenCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraResponse SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS.desactivarOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraRequest request) {
            return base.Channel.desactivarOrdenCompra(request);
        }
        
        public void desactivarOrdenCompra(int id) {
            SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraRequest inValue = new SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraRequest();
            inValue.id = id;
            SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraResponse retVal = ((SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS)(this)).desactivarOrdenCompra(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraResponse> SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS.desactivarOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraRequest request) {
            return base.Channel.desactivarOrdenCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraResponse> desactivarOrdenCompraAsync(int id) {
            SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraRequest inValue = new SoftProgWeb.ServicioOrdenCompraWS.desactivarOrdenCompraRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS)(this)).desactivarOrdenCompraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraResponse SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS.eliminarOrdenCompra(SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraRequest request) {
            return base.Channel.eliminarOrdenCompra(request);
        }
        
        public void eliminarOrdenCompra(int id) {
            SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraRequest inValue = new SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraRequest();
            inValue.id = id;
            SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraResponse retVal = ((SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS)(this)).eliminarOrdenCompra(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraResponse> SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS.eliminarOrdenCompraAsync(SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraRequest request) {
            return base.Channel.eliminarOrdenCompraAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraResponse> eliminarOrdenCompraAsync(int id) {
            SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraRequest inValue = new SoftProgWeb.ServicioOrdenCompraWS.eliminarOrdenCompraRequest();
            inValue.id = id;
            return ((SoftProgWeb.ServicioOrdenCompraWS.OrdenCompraWS)(this)).eliminarOrdenCompraAsync(inValue);
        }
    }
}
